### ISSUE TITLE
菜单配置问题

### ISSUE THREAD

**Issue by chengxulvtu** [dotnetcore/WTM#105]
1. 行内Action设置了SetOnClickScript，配置菜单时，动作里面没有这个Action，配置不了这个按钮的权限，最终也是无法显示这个按钮的。（QuickDebug==false）
2. OnClickFunc这个建议传入当前行的值，如下图所示
![image](https://user-images.githubusercontent.com/949848/67260926-acbdb700-f4d0-11e9-8573-cd72032dc9e2.png)

我项目里之所以用OnClickScript是因为点击按钮，需要连接到外部网站，同时传递当前行的一些信息。除了用单独一列，不知道有没有其他的写法？

3. 菜单管理-> 检查页面，有js错误。
4. 我修改了一个多租户的版本，但是改动比较多，不知道怎么跟现有合并，所以我想问一下，后面有没有支持多租户的打算？

**Comment by liuliang-wt** [comment]
1. 行内Action你也应该配置一个controller里的方法，虽然设置了script之后框架不会去调用后台方法，但是框架会判断那个方法的权限来决定是否显示这个按钮。
2. 这个建议很好，我们后期加上
3. 我这边复现不了
4.欢迎你在GitHub上提交PR，后面短期内我们并没有支持多租户的计划

**Comment by chengxulvtu** [comment]
好的，感谢，等我做完这个多租户的项目，整理一下提交PR。今天看你博客，最近要支持JWT,前段时间我也自己加入了JWT，就不提交这个了。
最后附上js的错误截图
![image](https://user-images.githubusercontent.com/949848/67266609-2eb6db80-f4e3-11e9-971f-9457b5a67126.png)

**Comment by liuliang-wt** [comment]
好奇怪，我这边没有这个错误，你是用的最新版本的框架么，清除缓存，换个浏览器之类的试试

**Comment by liuliang-wt** [comment]
那有可能是之前的bug，你用现在线上的生成一个新项目看看还有这个问题么
