### ISSUE TITLE
在向导快速配置打包WTM框架下载下来出错了。代码：MSB3086

### ISSUE THREAD

**Issue by 593172440** [dotnetcore/WTM#106]
不能运行，一上来就报错，我用的是vs2019最新版本
警告	NU1608	检测到的包版本在依赖项约束之外: Oracle.EntityFrameworkCore 2.19.30 需要 Microsoft.EntityFrameworkCore.Relational (>= 2.2.4 && < 3.0.0)，但版本 Microsoft.EntityFrameworkCore.Relational 3.0.0 已解决。	xxks.Test	D:\360极速浏览器下载\xxks\xxks.Test\xxks.Test.csproj	1		

警告	NU1608	检测到的包版本在依赖项约束之外: Oracle.EntityFrameworkCore 2.19.30 需要 Microsoft.EntityFrameworkCore.Relational (>= 2.2.4 && < 3.0.0)，但版本 Microsoft.EntityFrameworkCore.Relational 3.0.0 已解决。	xxks	D:\360极速浏览器下载\xxks\xxks\xxks.csproj	1		

错误	MSB3086	任务未能使用 SdkToolsPath“”或注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86”找到“al.exe”。请确保已设置 SdkToolsPath，在 SdkToolsPath 之下的相应处理器特定位置存在该工具，并且已安装 Microsoft Windows SDK	xxks	D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3639

**Comment by liuliang-wt** [comment]
那两个警告是因为oracle现在还不支持3.0，可以忽略。

至于你那个错误，因为多语言的资源文件需要al.exe支持才能编译，请确保你安装了WinSDK。如果你不需要多语言，可以把项目中Resources文件夹删除试试，他应该就不会寻找al.exe了

**Comment by SylvesterLi** [comment]
> 那两个警告是因为oracle现在还不支持3.0，可以忽略。
> 
> 至于你那个错误，因为多语言的资源文件需要al.exe支持才能编译，请确保你安装了WinSDK。如果你不需要多语言，可以把项目中Resources文件夹删除试试，他应该就不会寻找al.exe了

下面那个错误我也遇到了，除了要安装SDK还要添加环境变量。
变量名：TargetFrameworkSDKToolsDirectory
变量值：TargetFrameworkSDKToolsDirectory=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools

另：如果出现GenerateResource错误还要删除Resourcewen'jian文件夹内的东西
![image](https://user-images.githubusercontent.com/16554316/68530085-0a128e80-0340-11ea-8124-a8ab47b8e3d2.png)

**Comment by liuliang-wt** [comment]
新版本已经没有警告，但是如果你vs装的不全，还是会提示安装NetFx40Tools，可以在visual studio installer里面方便的安装：
![无标题6](https://user-images.githubusercontent.com/15852860/70976243-973ac700-20e6-11ea-9d92-29d99439c46e.png)
