### ISSUE TITLE
ef core生成数据报错

### ISSUE THREAD

**Issue by jacklmjie** [dotnetcore/WTM#107]
拉取的是master最新源码，我生成的是sqlserver，生成ef报了这个错
线上生成的项目，2.3.9的版本是对的
Add-Migration test
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: Object reference not set to an instance of an object.

**Comment by liuliang-wt** [comment]
这个问题在新版本已修复
