### ISSUE TITLE
生成ef报错

### ISSUE THREAD

**Issue by jacklmjie** [dotnetcore/WTM#108]
拉取的是master最新源码，demo中WalkingTec.Mvvm.Demo，生成的是sqlserver，生成ef报了这个错
Add-Migration init
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: Object reference not set to an instance of an object.
额...

**Comment by liuliang-wt** [comment]
你在没有数据库的情况下直接运行是可以自动生成数据库的，如果要用Migration，请参考文档
https://wtmdoc.walkingtec.cn/#/Data/Migration

**Comment by jacklmjie** [comment]
感谢您的回复，我今天在看下
我在使用过程中，在配置文件(appsettings.json)新增了字段,不是在AppSettings里，发现在不改变configs类情况下，扩展起来不是很方便，我能想到的方式
1.Configs用parent,可以不更改源码
2.新增类，再做一次读取appsettings.json
3.configs继承某接口，需要扩展新的类配置，实现这接口
或许您有更好的方式，感谢

**Comment by liuliang-wt** [comment]
现在你可以在appsettings文件中设置自定义的变量，比如：

 "AppSettings": {
    "Key1": "abc",
    "Key2": "123"
  }
然后通过 ConfigInfo.AppSettings["Key1"] 来访问
如果一定要通过ConfigInfo.Key1这种写法，你可以在你的代码里写一个ConfigInfo的扩展函数：

    public static class ConfigInfoExtension
    {
        public static string Key1(this Configs self)
        {
            return self.AppSettings["Key1"];
        }
    }

然后在controller和vm里通过 ConfigInfo.Key1() 来访问，当然最后还是要加个括号，毕竟是个方法，跟属性还不能完全一样，但是也清晰了不少。
