### ISSUE TITLE
[FEATURE] 能支持获取配置传入key值的写法吗？ var value = ConfigInfo.AppSettings["key"];

### ISSUE THREAD

**Issue by spookshadow** [dotnetcore/WTM#112]
如果没理解错，现在获取配置的写法：
var appsettings = ConfigInfo.AppSettings;
appsettings.First(s => s.Key == "ApiHost");
能否实现
var apiHost = ConfigInfo.AppSettings["ApiHost"];

**Comment by liuliang-wt** [comment]
好建议，下一版会更新

**Comment by liuliang-wt** [comment]
新版本已实现
