### ISSUE TITLE
如果WTM框架里再加入个工作流就完美了

### ISSUE THREAD

**Issue by lxkbest** [dotnetcore/WTM#113]

**Comment by liuliang-wt** [comment]
想得美，哦，不是，我是说你想的好。在vue和jwt完工之后后期会考虑，谢谢支持。

**Comment by lxkbest** [comment]
> 想得美，哦，不是，我是说你想的好。在vue和jwt完工之后后期会考虑，谢谢支持。

希望Vue版本 快速完工啊
