### ISSUE TITLE
如何增加 SignalR 支持？

### ISSUE THREAD

**Issue by ram16g** [dotnetcore/WTM#120]
如何改造 WTM 框架来实现 SignalR的支持？
自己按照 SignalR 的文档修改，不能实现。
能否提供一个小demo

**Comment by liuliang-wt** [comment]
wtm并没有阻止你使用其他包，signalr你自己添加应该可以。你如果有singalr的需求可以提出来，如果是普遍适用的，我们会考虑整合到框架中

**Comment by yottayuan** [comment]
建议@ram16g 研究一下，然后提个PR，这个功能真的很普遍适用啊

**Comment by yottayuan** [comment]
> wtm并没有阻止你使用其他包，signalr你自己添加应该可以。你如果有singalr的需求可以提出来，如果是普遍适用的，我们会考虑整合到框架中
现在网页要求实时更新的需求越来越多，Core3中的Blazor的服务端机制就是SignalR，建议尽快增加啊
