### ISSUE TITLE
项目不能自动生成数据库

### ISSUE THREAD

**Issue by guodongme123** [dotnetcore/WTM#124]
文档比较简单，不知道是哪里有问题。项目运行后不能自动生成数据库，但是自己手动建库后可以正常运行。
而且数据库中没有表的存在，求解答

**Comment by beyond1983** [comment]
Nuget管理控制台使用EF命令行，手动执行数据库变更。






&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"guodongme123"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 上午9:46
收件人:&nbsp;"dotnetcore/WTM"<WTM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dotnetcore/WTM] 项目不能自动生成数据库 (#124)




文档比较简单，不知道是哪里有问题。项目运行后不能自动生成数据库，但是自己手动建库后可以正常运行。
 而且数据库中没有表的存在，求解答

**Comment by liuliang-wt** [comment]
系统在你没有数据库的情况下，会自动建库建表，如果没有自动建库，应该是连接字符串的问题，你可与i注意一下系统启动时候的输出，建库失败会有错误提示

**Comment by guodongme123** [comment]
谢谢回复，已解决
