### ISSUE TITLE
希望刘总能够增加一个数据字典的功能

### ISSUE THREAD

**Issue by iceunlim** [dotnetcore/WTM#126]
枚举还是少了一些灵活性，希望能够自带一个数据字典功能。

**Comment by liuliang-wt** [comment]
数据字典功能并不复杂，只是有利有弊。如果用数据字典，带枚举字段的查询就需要关联字典表，效率上可能是个问题。另外如果需要多语言的话，字典表还需要实现数据的多语言，增加了整个系统的复杂度。
