### ISSUE TITLE
表格主题 Material 样式异常

### ISSUE THREAD

**Issue by ram16g** [dotnetcore/WTM#130]
表格主题 Material 很漂亮
但是样式异常，见下图
![1](https://user-images.githubusercontent.com/11473136/68287237-6023cf80-00bd-11ea-831f-353f0c8df782.png)
另一个主题
![2](https://user-images.githubusercontent.com/11473136/68287355-8cd7e700-00bd-11ea-9212-abc7f3f3f8f3.png)

**Comment by LengYXin** [comment]
收到~ ~

**Comment by LengYXin** [comment]
默认选择 Material F5刷新页面也是这样的么

**Comment by ram16g** [comment]
> 默认选择 Material F5刷新页面也是这样的么

今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式

**Comment by LengYXin** [comment]
> > 默认选择 Material F5刷新页面也是这样的么
> 
> 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式

浏览器 是那个

**Comment by ram16g** [comment]
> > > 默认选择 Material F5刷新页面也是这样的么
> > 
> > 
> > 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式
> 
> 浏览器 是那个

我测试了一下火狐和 chrome 浏览器都有这个问题

Firefox 70.0.1 (64 位)
Google Chrome 版本 78.0.3904.97（正式版本） （64 位）

**Comment by LengYXin** [comment]
> > > > 默认选择 Material F5刷新页面也是这样的么
> > > 
> > > 
> > > 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式
> > 
> > 
> > 浏览器 是那个
> 
> 我测试了一下火狐和 chrome 浏览器都有这个问题
> 
> Firefox 70.0.1 (64 位)
> Google Chrome 版本 78.0.3904.97（正式版本） （64 位）
> 
> 我创建项目的时候选择的是 .netcore 2.2，样式异常的页面是我自己新增的学校管理模块，系统自带的其他模块的样式正常。

图一的原因是了解了。图二的原因还不明。在系统管理中的那些页面有这么问题么

**Comment by ram16g** [comment]
> 
> 
> > > > > 默认选择 Material F5刷新页面也是这样的么
> > > > 
> > > > 
> > > > 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式
> > > 
> > > 
> > > 浏览器 是那个
> > 
> > 
> > 我测试了一下火狐和 chrome 浏览器都有这个问题
> > Firefox 70.0.1 (64 位)
> > Google Chrome 版本 78.0.3904.97（正式版本） （64 位）
> > 我创建项目的时候选择的是 .netcore 2.2，样式异常的页面是我自己新增的学校管理模块，系统自带的其他模块的样式正常。
> 
> 图一的原因是了解了。图二的原因还不明。在系统管理中的那些页面有这么问题么

系统管理的那些页面是正常的。
图二的样式是正常的，我发图是为了对比，我觉得图二中表格的行高再大一点就更美观了

**Comment by LengYXin** [comment]
> > > > > > 默认选择 Material F5刷新页面也是这样的么
> > > > > 
> > > > > 
> > > > > 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式
> > > > 
> > > > 
> > > > 浏览器 是那个
> > > 
> > > 
> > > 我测试了一下火狐和 chrome 浏览器都有这个问题
> > > Firefox 70.0.1 (64 位)
> > > Google Chrome 版本 78.0.3904.97（正式版本） （64 位）
> > > 我创建项目的时候选择的是 .netcore 2.2，样式异常的页面是我自己新增的学校管理模块，系统自带的其他模块的样式正常。
> > 
> > 
> > 图一的原因是了解了。图二的原因还不明。在系统管理中的那些页面有这么问题么
> 
> 系统管理的那些页面是正常的。
> 图二的样式是正常的，我发图是为了对比，我觉得图二中表格的行高再大一点就更美观了

行高是有属性可配置的。rowHeight 在table 组件当中使用。可以参考frameworkuser>view>table.tsx 48行

**Comment by ram16g** [comment]
> > > > > > > 默认选择 Material F5刷新页面也是这样的么
> > > > > > 
> > > > > > 
> > > > > > 今天新建的项目，默认是 Material 主题，刷新以后还是这样的样式
> > > > > 
> > > > > 
> > > > > 浏览器 是那个
> > > > 
> > > > 
> > > > 我测试了一下火狐和 chrome 浏览器都有这个问题
> > > > Firefox 70.0.1 (64 位)
> > > > Google Chrome 版本 78.0.3904.97（正式版本） （64 位）
> > > > 我创建项目的时候选择的是 .netcore 2.2，样式异常的页面是我自己新增的学校管理模块，系统自带的其他模块的样式正常。
> > > 
> > > 
> > > 图一的原因是了解了。图二的原因还不明。在系统管理中的那些页面有这么问题么
> > 
> > 
> > 系统管理的那些页面是正常的。
> > 图二的样式是正常的，我发图是为了对比，我觉得图二中表格的行高再大一点就更美观了
> 
> 行高是有属性可配置的。rowHeight 在table 组件当中使用。可以参考frameworkuser>view>table.tsx 48行
> 但是 默认的情况下 不像是frameworkuser 这种特殊的 表格是不会出现这样的问题的。目前我没确定出在哪了。方便的话 在QQ群中把好的 pages模块代码 发送给我 能更好的定位问题所在

辛苦了，按照你的指导，问题解决了，修改了对应页面 table.tsx，别忘了修改代码生成器 : )
![TIM截图20191107220253](https://user-images.githubusercontent.com/11473136/68395295-68a60400-01aa-11ea-8977-c851fe2aa958.png)
