### ISSUE TITLE
如何扩展LoginUserInfo

### ISSUE THREAD

**Issue by looogbao** [dotnetcore/WTM#136]
我想在LoginUserInfo中增加一个字段，可以直接继承LoginUserInfo这个类添加自己需要的字段，然后重写Login的方法，这样做可以吗

**Comment by liuliang-wt** [comment]
不可以，因为LoginUserInfo最终是要保存在Session中，你继承的类框架并不知道。 LoginUserInfo有一个Attributes属性，你可以储存和读取key，value格式的数据

**Comment by looogbao** [comment]
OK，多谢
