### ISSUE TITLE
Add constructor to FrameworkContext so that it can be register to DBContextPool.

### ISSUE THREAD

**Issue by sheng-jie** [dotnetcore/WTM#139]
I have another console project which depends on DataAccess project directly. But I cannot register the DataContext to the DI directly. I need an constructor like below so that I can register DataContext as DbContextPool. Without out it, it will show the error like that *The DbContext of type 'DataContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions.*

```
public FrameworkContext(DbContextOptions<FrameworkContext> options) : base(options){}
```

Thanks.

* PS:  Another question: After update  from 3.0.0 to 3.0.1, the web cannot login*

**Comment by liuliang-wt** [comment]
ok, I will add that constructor in the next release.
about 3.0.1, because 3.0.1 supports JWT now , it's login logic changes abit. You can create a new project from our website, and copy the generated LoginVM.cs to your exist project, and it will work.

**Comment by sheng-jie** [comment]
Thanks, close it!

**Comment by sheng-jie** [comment]
@liuliang-wt  I followed your suggestion to update the project, but still cannot login.
I compared the LoginVM and there is no difference between them.

**Comment by sheng-jie** [comment]
The constructor hasn't been added yet. Please help to check.

**Comment by liuliang-wt** [comment]
Added， please wait for the next release which will be soon
