### ISSUE TITLE
建议增加顶部菜单导航设置

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#14]
前后端分离react版本，当前的实现，菜单的布局在左侧（side-menu），占用了屏幕主区域的不少空间。
建议增加导航菜单在顶部的设置，可以设置导航菜单在顶部显示，如下图：
<img width="1432" alt="屏幕快照 2019-04-29 10 40 56" src="https://user-images.githubusercontent.com/9619081/56874364-11411180-6a6c-11e9-94ec-d64732c97dd5.png">

**Comment by liuliang-wt** [comment]
@LengYXin 考虑一下，在global里加一个配置选项，来选择菜单位置

**Comment by liaoyongxiong** [comment]
请问，此问题何时才能修改？

**Comment by liuliang-wt** [comment]
@LengYXin 冷哥，还有这个

**Comment by liaoyongxiong** [comment]
@LengYXin 冷哥，还有这个

**Comment by LengYXin** [comment]
> @LengYXin 冷哥，还有这个

下一次提交更新！

**Comment by LengYXin** [comment]
@liuliang-wt @liaoyongxiong 已添加

**Comment by liaoyongxiong** [comment]
开发完成，关闭
