### ISSUE TITLE
core2.2 react 版本 自动生成代码 提交后出现以下异常

### ISSUE THREAD

**Issue by Newxml** [dotnetcore/WTM#140]
![image](https://user-images.githubusercontent.com/34527830/69033835-d3610600-0a1a-11ea-8d3d-0b63786dd3d9.png)
System.NullReferenceException: Object reference not set to an instance of an object.</br>   at WalkingTec.Mvvm.Core.PropertyHelper.GetMemberType(MemberInfo mi)</br>   at WalkingTec.Mvvm.Core.PropertyHelper.IsPropertyRequired(MemberInfo pi)</br>   at WalkingTec.Mvvm.Mvc.CodeGenVM.GenerateReactView(String name)</br>   at WalkingTec.Mvvm.Mvc.CodeGenVM.DoGen()</br>   at WalkingTec.Mvvm.Mvc._CodeGenController.DoGen(CodeGenVM vm)</br>   at lambda_method(Closure , Object , Object[] )</br>   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)</br>   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)</br>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()</br>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()</br>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)</br>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)</br>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()</br>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()</br>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)</br>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)</br>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()</br>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()</br>   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)</br>   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)</br>   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)</br>   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)</br>   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)</br>   at WalkingTec.Mvvm.Mvc.FrameworkServiceExtension.<>c__DisplayClass1_0.<<UseFrameworkService>b__0>d.MoveNext()</br>--- End of stack trace from previous location where exception was thrown ---</br>   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)</br>   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)</br>   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)</br>   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)</br>   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by liuliang-wt** [comment]
你好，可以把报错的这个model发给我看一下么
