### ISSUE TITLE
多表关联验证问题

### ISSUE THREAD

**Issue by Evring** [dotnetcore/WTM#142]
多表关联，添加数据时它会验证关联表的字段有没有值

**Comment by liuliang-wt** [comment]
请举例具体描述，谢谢

**Comment by Evring** [comment]
For Example：
我 EnterpriseLibrary 表里一对一关联 MyUser 表，前端使用Combobox 显示下拉，保存的时候会验证MyUser的字段，还有保存的时候MyUser的ID没有保存进去。

我看了下源码知道是怎么做的了。
public Guid? UserId { get; set; }
[JsonIgnore()]
public FrameworkUserBase User { get; set; }

是加了2个字段，忽略了实体类映射数据库，
然后重写了Validate，跟DoAdd方法。

感觉这块应该是改下DoAdd的反射方法就可以搞定啊。这么弄好麻烦..

**Comment by liuliang-wt** [comment]
前端combobox只绑定UserId就可以，并不需要User这个类

**Comment by Evring** [comment]
好的，多谢
