### ISSUE TITLE
[Fearure]建议框架增加多租户支持

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#15]
维基百科中是这样定义多租户的:
软件多租户技术指的是一种软件架构,这种架构可以使用软件的单实例运行并为多个租户提供服务.租户是通过软件实例的特定权限共享通用访问的一组用户.使用多租户架构,软件应用为每个租户提供实例的专用共享,包括实例的数据、配置、用户管理、租户的私有功能和非功能属性.多租户与多实例架构形成对比,将软件实例的行为根据不同的租户分割开来.

关于多租户的支持及实现，可以参考ABP框架：https://cn.abp.io/documents/abp/latest/Multi-Tenancy

**Comment by liuliang-wt** [comment]
这个目前可以通过在框架内自定义用户，把用户和某个组织关联起来来实现，框架原生的支持可能要比较靠后了。
