### ISSUE TITLE
当搜索条件只有一个时，在搜索框中按回车键会出现异常页面。

### ISSUE THREAD

**Issue by iceunlim** [dotnetcore/WTM#151]
版本是.net3.0 layui版
![TIM图片20191125145017](https://user-images.githubusercontent.com/19189141/69518588-ee8bc280-0f92-11ea-9161-88df5cca5013.png)
![TIM图片20191125145023](https://user-images.githubusercontent.com/19189141/69518590-ef245900-0f92-11ea-919f-8806dbaf006e.png)

**Comment by liuliang-wt** [comment]
@alienwow
