### ISSUE TITLE
ReactDemo 执行 yarn start 出错,真想看看该项目前后端分离的效果...

### ISSUE THREAD

**Issue by jinwmmail** [dotnetcore/WTM#153]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
▶ 27 stack frames were collapsed.
Store._callee$
D:/_WTM/WTM-2.4.2/demo/WalkingTec.Mvvm.ReactDemo/ClientApp/src/store/system/user.ts:37
  34 |     this.UserInfo = userInfo;
  35 |     this.Actions = lodash.map(lodash.get(userInfo, 'Attributes.Actions', []), lodash.toLower);
  36 |     await Menu.onInitMenu(lodash.get(userInfo, 'Attributes.Menus', []));
> 37 |     runInAction(() => {
     | ^  38 |         this.isLogin = true;
  39 |     })
  40 | }

谁能帮帮我?

**Comment by LengYXin** [comment]
node 版本，yarn 版本分别是多少。建议使用11以上的node npm 镜像地址指向淘宝镜像

**Comment by jinwmmail** [comment]
@LengYXin 您好，node 升级到最新版，然后使用 cnpm 成功了，但是同样的操作，换一台电脑就不行.
另外，我把 yarn 升级到最新版，怎么弄都不成功.

**Comment by LengYXin** [comment]
> @LengYXin 您好，node 升级到最新版，然后使用 cnpm 成功了，但是同样的操作，换一台电脑就不行.
> 另外，我把 yarn 升级到最新版，怎么弄都不成功.

使用 npm 或者 yarn 安装依赖。推荐yarn
