### ISSUE TITLE
[Feature]前后端分离React版本，菜单管理中菜单项增加、修改时可支持选取Ant Design图标

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#16]
支持选取Ant Design图标的好处：对于小团队，可以直接重用大厂设计好的图标，降低UI设计开发难度。如下图：
<img width="786" alt="屏幕快照 2019-04-29 15 14 31" src="https://user-images.githubusercontent.com/9619081/56881250-67c14680-6a92-11e9-9624-9cfa996fdd15.png">

**Comment by liaoyongxiong** [comment]
Ant Design图标的使用，可以参考这个=》https://ant.design/components/icon-cn/

**Comment by liuliang-wt** [comment]
@LengYXin  前端大神，考虑一下，我们要重视来自群众的呼声  :)

**Comment by LengYXin** [comment]
> Ant Design图标的使用，可以参考这个=“ https://ant.design/components/icon-cn/

ok，没问题

**Comment by liaoyongxiong** [comment]
请问，此问题何时才能修改？

**Comment by liuliang-wt** [comment]
@LengYXin 冷哥最近比较忙，抽时间改一下吧

**Comment by LengYXin** [comment]
> 请问，此问题何时才能修改？

已更新。
