### ISSUE TITLE
关于调试自定义view的问题

### ISSUE THREAD

**Issue by w452844226** [dotnetcore/WTM#169]
请问，我自己用js写了一个view，请问如何调试前端，Chrome浏览器抓不到js，不知道该如何调试

**Comment by liuliang-wt** [comment]
框架封装的js在 framework_layui.js中，如图：
![无标题](https://user-images.githubusercontent.com/15852860/70970308-ff82ac00-20d8-11ea-8b5a-c398be86e684.png)

如果是你自己写的js，最简单的办法是在你要调试的地方加debugger;，这样运行到这句话的时候，如果你浏览器开着F12，就会自动进入断点，如图：

![无标题1](https://user-images.githubusercontent.com/15852860/70970582-ae26ec80-20d9-11ea-86bb-de55007614b5.png)
