### ISSUE TITLE
如何写js控制画面，比如有个checkbox，勾选了，相应输入框就有效

### ISSUE THREAD

**Issue by soundsun** [dotnetcore/WTM#170]
如何写js控制画面，比如有个checkbox，勾选了，相应输入框就有效

**Comment by liuliang-wt** [comment]
checkbox, combobox 等控件可以指定change-func属性，当控件值发生变化时会调用 change-func所指定的前台js函数，如图：

![无标题2](https://user-images.githubusercontent.com/15852860/70971602-52aa2e00-20dc-11ea-98d2-3e8a00918895.png)

**Comment by liuliang-wt** [comment]
另外， change-func指定的js方法可以带一个参数，你可以把鼠标放在change-func上来查看参数的具体内容，比如下图弹出的是combbox选中的值
![无标题3](https://user-images.githubusercontent.com/15852860/70971875-ee3b9e80-20dc-11ea-83e2-95d87239a67e.png)
