### ISSUE TITLE
如何在搜索条件里面对日期 字段增加开始及结束查询条件

### ISSUE THREAD

**Issue by haoxiangxiang** [dotnetcore/WTM#171]
如何在搜索条件里面对日期 字段增加开始及结束查询条件

**Comment by faust8883** [comment]
Searcher中增加StartDate和EndDate，然后在ListVM的GetSearchQuery中增加过滤条件即可。

**Comment by liuliang-wt** [comment]
@faust8883 同学说的对，在Searcher中添加两个变量，然后前台用两个时间控件绑定这两个变量，后台就可以获取到了。

另外，框架提供了一个DataRange类，用于简化这种时间区间的定义，比如，你可以在Searcher里定义：
public DateRange EnRollDateRange { get; set; }

然后在前台绑定
<wt:datetime field="Entity.EnRollDateRange" min="2018-01-01" max="2038-08-01" type="Date" range="true" confirm-only="true"/>

就会有这种效果：

![无标题5](https://user-images.githubusercontent.com/15852860/70973028-c3067e80-20df-11ea-8e05-691a2ddebd1f.png)

你在后台可以获取DataRange变量中的开始时间和结束时间

**Comment by ChiLoneYu** [comment]
System.NullReferenceException:“Object reference not set to an instance of an object.”
<wt:datetime>EnRollDateRange首次加载获取不到为NULL值。
xxxx_WTMSearcher.EnRollDateRange.get 返回 null。


> @faust8883 同学说的对，在Searcher中添加两个变量，然后前台用两个时间控件绑定这两个变量，后台就可以获取到了。
> 
> 另外，框架提供了一个DataRange类，用于简化这种时间区间的定义，比如，你可以在Searcher里定义：
> public DateRange EnRollDateRange { get; set; }
> 
> 然后在前台绑定
> <wt:datetime field="Entity.EnRollDateRange" min="2018-01-01" max="2038-08-01" type="Date" range="true" confirm-only="true"/>
> 
> 就会有这种效果：
> 
> ![无标题5](https://user-images.githubusercontent.com/15852860/70973028-c3067e80-20df-11ea-8e05-691a2ddebd1f.png)
> 
> 你在后台可以获取DataRange变量中的开始时间和结束时间

**Comment by liuliang-wt** [comment]
它有可能是控制，如果你查询页面没有选择时间那就是空值啊，你用xxxx_WTMSearcher.EnRollDateRange?.GetStartTime() 这种写法

**Comment by ChiLoneYu** [comment]
> 它有可能是空值，如果你查询页面没有选择时间那就是空值啊，你用xxxx_WTMSearcher.EnRollDateRange?.GetStartTime() 这种写法

不知道为什么返回的日期格式总是{2019/12/1 0:00:00}   Date: {2019/12/1 0:00:00} 查询时就字符串转换日期和/或时间时，转换失败。” 用datetime和DateRange控件都是这个错误。
