### ISSUE TITLE
如何通过js获取Tree选中节点的数据

### ISSUE THREAD

**Issue by w452844226** [dotnetcore/WTM#174]
貌似layui没有提供相关获取Tree选中(非checkbox)节点数据的方法

**Comment by liuliang-wt** [comment]
框架封装的<wt:tree>组件实际上加入了一个和你绑定字段同名的hidden，所以你可以用js获取那个hidden的值

**Comment by w452844226** [comment]
我用的是TreeContainer,请问这个是对应哪个字段，item,还是id-field?
