### ISSUE TITLE
请问如何设置使用多个数据库？

### ISSUE THREAD

**Issue by 2360673637** [dotnetcore/WTM#177]
请问如何设置使用多个数据库？

**Comment by haoljp** [comment]
同问。如何设置多个数据库用户连接？

**Comment by 2360673637** [comment]
https://wtmdoc.walkingtec.cn/#/Global/CS
刚才看到文档里面有说的，不知道是否可以，正在学习

**Comment by zhaohl2045** [comment]
> 请问如何设置使用多个数据库？

DataContext DCNew = new DataContext("Key", DBTypeEnum.SqlServer); Key代表你在ConnectionString中配置的Key。

**Comment by zhaohl2045** [comment]
DataContext DCNew = new DataContext("Key", DBTypeEnum.SqlServer); Key代表你在ConnectionString中配置的Key。

**Comment by liuliang-wt** [comment]
@2360673637 如文档所描述的，你可以在controller或者controller里面的方法上使用[FixConnection]标记来指定这里面的dc使用另一个数据库连接。 当然你也可以直接 new DataContext();


@zhaohl2045 new DataContext()的时候，第一个参数是实际的连接字符串，而不是ConnectionString里的key
