### ISSUE TITLE
没有出现在view的字段怎么在controler更新？

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#178]
vm.Entity.jcry = LoginUserInfo.Name;
vm.Entity.jcsj = DateTime.Now;
vm.DoEdit();

这样不行吗？
纯 net core 新手。。。

**Comment by vthe** [comment]
纯 net core 新手。。。

**Comment by vthe** [comment]
vm.Entity.jcry =LoginUserInfo.Name;
                vm.Entity.jcsj = DateTime.Now;

                vm.FC.Add("Entity.jcry", LoginUserInfo.Name);
                vm.FC.Add("Entity.jcsj", DateTime.Now);
这样就可以了

**Comment by liuliang-wt** [comment]
@vthe 是的，框架为了安全考虑，只会更新你表单提交的字段，如果要更新其他字段，可以通过vm.FC.Add来添加key，value，假装表单提交了这些数据。。。

或者你也可以使用vm.DoEdit(true); 来强制更新Entity里的所有字段，但这种方式对于字段很多的数据，很容易忘记给某个字段赋值导致字段被更新成空值。

**Comment by vthe** [comment]
谢谢解释。 但经过我测试，更新时候，保存到数据库的value 是vm.Entity的值，不是 vm.FC.Add这边添加的value。

**Comment by liuliang-wt** [comment]
是的，FC中的只是为了判断是否是表单提交的，实际值还是从Entity中读取，所以其实你写成

vm.FC.Add("Entity.jcry", 1);
vm.FC.Add("Entity.jcsj", 1);
就行

**Comment by vthe** [comment]
明白了。感谢
