### ISSUE TITLE
关于使用IIS部署完成后登录界面无法进入的问题

### ISSUE THREAD

**Issue by punisherCN** [dotnetcore/WTM#179]
今天，在Win7系统上安装了IIS，也在VS2019中进行了发布，遇到的问题是：
在IIS中，点击访问网站，默认打开的是360浏览器，可以正常登陆。但是，如果在360浏览器中，访问一样的本地地址127.0.0.1就无法登陆。更有意思的是直接使用谷歌的浏览器访问本地地址，可以登陆。新手，不太明白这其中的原理，看看哪位能帮着解答一下，先谢过了。

**Comment by liuliang-wt** [comment]
你说的无法登陆，是说可以出现登陆页面但是点登陆报错，还是连登陆页面都出不来？

**Comment by punisherCN** [comment]
不好意思，今天早上试了一下，使用的是admin作为用户名，没有出现过上述的问题。昨天使用的是test作为用户名。感谢您那么晚了，还给回答，谢谢。
