### ISSUE TITLE
[Bug]前后端分离版本代码生成界面，View部分的文件名及路径显示不正确

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#18]
前后端分离react版本，代码生成页面，显示的View文件名和路径跟ClientApp下的页面对应不起来，如下入：
生成的文件名及路径如下：
<img width="324" alt="屏幕快照 2019-04-30 10 26 00" src="https://user-images.githubusercontent.com/9619081/56938131-cdfda600-6b32-11e9-8008-5889fb2f5c4c.png">

显示的路径却是下面的，跟实际对应不起来：
<img width="1437" alt="屏幕快照 2019-04-30 10 13 09" src="https://user-images.githubusercontent.com/9619081/56938154-e79eed80-6b32-11e9-8f09-9cf1a1840a51.png">

**Comment by liuliang-wt** [comment]
是的，React版本的代码生成器目前还是借用前后端不分离的代码生成器，后续会彻底更换成React版本的
