### ISSUE TITLE
查询数据到前段

### ISSUE THREAD

**Issue by hanshuhe** [dotnetcore/WTM#180]
亮总你好，代码生成器生成好代码后（多层layui），按照例子写的一个Schoo模型，代码生成器生成相关代码了，并且可以在后台跑起来了，可以实现School增删改查，我想自己写代码来实现在前段（自己重新定义的页面）来显示数据库里的一条记录，思路是什么样的，比如在SchoolController里要写什么，在SchoolVM里写什么？不知道怎么把数据查出来，比如就查询第一条数据。能给个代码段吗？非常感谢！

**Comment by liuliang-wt** [comment]
代码生成器应该已经给你把前后台都生成好了，如果你要手工显示某一条记录，你可以参考生成的代码里的Controller里的Details方法，那个就是根据id显示数据信息的。

**Comment by hanshuhe** [comment]
亮总你好，之前我也看了Details的那个方法，还设置断点进去看的。但是看不到什么内容的，因为都是继承了你类库的方法。我们也看不到具体怎么实现的。我建议，既然是开源的，那么你生成代码的时候，就直接把生成带源码的，而不是用类库的。这样我们用起来可以改变的东西更多，可以参考的东西也更多
