### ISSUE TITLE
我想在子父表之间实现日期查询

### ISSUE THREAD

**Issue by haoxiangxiang** [dotnetcore/WTM#182]
1、我想在子父表之间实现日期查询？
2、如何使用checkWhere方法，具体的用法？
3、如何自定义查询条件？

**Comment by haoxiangxiang** [comment]
目前自己在 “CTL”及 亮哥 的帮助下，已解决了该问题。
解决方法：
使用where条件查询，可以解决
var query = DC.Set<InstallProduct>()
               .CheckEqual(Searcher.CustomerId, x => x.CustomerId)
               .CheckEqual(Searcher.ProductId, x => x.ProductId)
               .CheckEqual(Searcher.SendFlag, x => x.SendFlag)
               .CheckContain(Searcher.AnZhuangRen, x => x.AnZhuangRen)
               .CheckBetween(Searcher.SaleDateStart, Searcher.SaleDateEnd, x => x.SaleDate)
               .CheckBetween(Searcher.BaoXiuDateStart, Searcher.BaoXiuDateEnd, x => x.BaoXiuDate)
               .CheckBetween(Searcher.AnZhuangDateStart, Searcher.AnZhuangDateEnd, x => x.AnZhuangDate)
               .CheckBetween(Searcher.GengHuanDateStart, Searcher.GengHuanDateEnd, x => x.GengHuanDate)
               .CheckContain(Searcher.HeTongNum, x => x.HeTongNum)
               .Where(x => (DateTime.Now - (DateTime)x.GengHuanDate).TotalDays > x.Product.LimitDate)
               .Select(x => new InstallProduct_View
               {
                   ID = x.ID,
                   CustomName_view = x.Customer.CustomName,
                   ProductName_view = x.Product.ProductName,
                   SendFlag = x.SendFlag,
                   HuiFang = x.HuiFang,
                   SalePrice = x.SalePrice,
                   AnZhuangRen = x.AnZhuangRen,
                   SaleDate = x.SaleDate,
                   BaoXiuDate = x.BaoXiuDate,
                   AnZhuangDate = x.AnZhuangDate,
                   GengHuanDate = x.GengHuanDate,
                   HeTongNum = x.HeTongNum,
                   Remark = x.Remark,
               })
               .OrderBy(x => x.ID);
注意“.Where(x => (DateTime.Now - (DateTime)x.GengHuanDate).TotalDays > x.Product.LimitDate)”这行代码，这行必须写在select之前，因为select时，EF是不会加载对应子表里的数据（x.Product.LimitDate）也就是这个product里面是不会有值的，而select之后的where语句，是在select查询出数据后，再次where过滤的，如果在select之后加x.Product.LimitDate，则会报空指针异常。
将where放到select 之前，因为该 where 条件中写了要用到子表数据（x.Product.LimitDate），所以EF会自动加载子表里的数据。

**Comment by liuliang-wt** [comment]
你这样写是可以正常运行，但是EF会获取所有数据到本地再分页，因为他翻译不了 (DateTime.Now - (DateTime)x.GengHuanDate).TotalDays > x.Product.LimitDate) 这句话，你数据量小看不出来，数据量大了就很慢了。正确的写法应该是使用EF提供的数据库函数，比如：

Where(x=> EF.Functions.DateDiffDay(x.GengHuanDate,DateTime.Now)> x.Product.LimitDate)  

EF.Functions里提供了一些常用的日期，字符串之类的数据库端的函数
