### ISSUE TITLE
一个combobox选择后，联动2个combobox，这两个的items是一样的，如何处理？

### ISSUE THREAD

**Issue by soundsun** [dotnetcore/WTM#183]

**Comment by liuliang-wt** [comment]
框架目前提供的方法智能是A联动B，不能A同时联动B和C，但是你可以A联动B，B联动C，缺点就是B联动C的时候也会调用一遍后台接口。
另一种方式就是不用框架提供的联动，而是在combobox上指定ChangeFunc，然后自己写联动需要的js
