### ISSUE TITLE
照片预览自适应

### ISSUE THREAD

**Issue by Jddl** [dotnetcore/WTM#184]
![image](https://user-images.githubusercontent.com/11550798/71137390-f4e42600-2242-11ea-9b94-d322171434d7.png)
照片预览如何大小自适应？

**Comment by liuliang-wt** [comment]
框架自带的预览按钮本身是自适应的，你这个情况有可能是因为你的上传控件设定了缩略图的宽度和高度，比如，假如你上传控件是这样定义的
 <wt:upload field="Entity.PhotoId" upload-type="ImageFile" thumb-width="300" thumb-height="100" />
那么框架在上传的时候就已经把图片缩放成 300*100的大小了

**Comment by Jddl** [comment]
框架代码上传的，并没有手动修改宽度高度
![image](https://user-images.githubusercontent.com/11550798/71155166-29260980-2278-11ea-887d-0f46c21cb18a.png)
![211422199412226219](https://user-images.githubusercontent.com/11550798/71155242-465ad800-2278-11ea-9c20-e6ade9b3c5b7.jpg)
好像是donotuse_pdiv这个css导致的，去掉display属性就ok。
但会导致列表在IE浏览器上不正常。
在图像预览里去掉donotuse_pdiv包裹即可

**Comment by liuliang-wt** [comment]
哦，你看一下你的ListVM，指定这个预览按钮的部分，是不是指定了弹出窗口的尺寸，类似这样的：
ColumnFormatInfo.MakeViewButton(ButtonTypesEnum.Button,entity.PhotoId,640,480),

你把最后两个参数去掉，弹出窗口就是自适应了

**Comment by Jddl** [comment]
确实是这个问题☺

**Comment by vthe** [comment]
删了后面的两个参数后，显示成原图大小了。 也不太对。

**Comment by vthe** [comment]
特别是大像素的照片。直接充满这个屏幕。
