### ISSUE TITLE
upload上传文件大小限制

### ISSUE THREAD

**Issue by 401175209** [dotnetcore/WTM#185]
<img width="560" alt="WX20191219-122752@2x" src="https://user-images.githubusercontent.com/8400786/71145063-1d781a00-225b-11ea-9892-0723e4a4ba49.png">
小文件没问题。上传大文件报错，怎么解决？

**Comment by 401175209** [comment]
使用自带upload控件，代码生成器生成的代码

**Comment by liuliang-wt** [comment]
你是本地调试还是发布到比如IIS之后这样？

**Comment by yottayuan** [comment]
如果是在IIS上发布的，IIS默认允许上传的最大文件时30000000B，需要进入IIS对应网站下，点击右侧的配置编辑器，下拉节(S),选中节点system.webServer/security/requestFiltering下，点击下拉requestLimits>maxAllowedContentLength,将30000000设置成你想要的大小，比如：102400000(即100m)，1024000000(即1个G)

**Comment by 401175209** [comment]
我是本地调试

**Comment by liuliang-wt** [comment]
@401175209 你本地调试默认也是用IIS express调试的，你可以试试用命令行的方式调试。另外，你说的大文件是多大？

**Comment by 401175209** [comment]
我用的kestrel，在Linux上

**Comment by liuliang-wt** [comment]
那你看看kestrel输出窗口里应该有具体报错的信息

**Comment by 401175209** [comment]
4M以上文件都报错，以下没问题

**Comment by liuliang-wt** [comment]
你检查一下appsettings里文件上传部分的配置

**Comment by 401175209** [comment]
![image](https://user-images.githubusercontent.com/8400786/71153955-650b9f80-2275-11ea-8a12-0906228a6f62.png)

**Comment by 401175209** [comment]
"FileUploadOptions": {
    "UploadLimit": 20971520,
    "SaveFileMode": "Database", //上传文件的保存方式，可选Database,local,dfs
    "UploadDir": ""    //当上传文件选择Local时，指定硬盘目录
  },

**Comment by yottayuan** [comment]
因为你是上传到数据库中，所以，应该是数据库上传二进制数据的大小限制了：例如：mysql > set global max_allowed_packet = 1024*1024*10;  大文件不推荐上传到数据库哦。

**Comment by liuliang-wt** [comment]
@yottayuan 同学的猜测有可能是对的，你看看命令行输出的错误应该能找到具体的问题

**Comment by 401175209** [comment]
嗯，我换换成local试试
