### ISSUE TITLE
Middleware context.User.Identity.IsAuthenticated总是false

### ISSUE THREAD

**Issue by harvey0720** [dotnetcore/WTM#188]
用户登录后，在中间件里获取当前用户是否验证通过，总是不成功。
关键代码如下：
Configure(x =>
                {
                    x.UseMiddleware<MyMiddleware>(); //--这里增加中间件
                    var configs = x.ApplicationServices.GetRequiredService<Configs>();
                    if (configs.IsQuickDebug == true)
                    {
                        x.UseSwagger();
                        x.UseSwaggerUI(c =>
                        {
                            c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
                        });
                    }
                    x.UseFrameworkService(); 

中间件内容：
 public async Task Invoke(HttpContext context)
            {          
                    if (!context.User.Identity.IsAuthenticated)//--这里获取到值总是false
                    {
                        await Task.CompletedTask;
                        return;
                    }
                    await _next.Invoke(context);
                }
是用法不对？谢谢

**Comment by alienwow** [comment]
顺序不对，x.UseFrameworkService内包含 UseAuthentication中间件，你所添加的中间件需要在这之后才有效

```csharp
Configure(x =>
{
var configs = x.ApplicationServices.GetRequiredService();
if (configs.IsQuickDebug == true)
{
x.UseSwagger();
x.UseSwaggerUI(c =>
{
c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});
}
x.UseFrameworkService();
x.UseMiddleware(); //--这里增加中间件
```

**Comment by harvey0720** [comment]
放到x.UseFrameworkService();下面对于未经过Controller的访问是可以的。如果直接通过Controller/Action访问的方式，这个中间件就失效了。不过，通过变通也是可以实现的。

**Comment by alienwow** [comment]
你说的这个正在重构，后面都会抽离出来，自由组合中间件
