### ISSUE TITLE
关于数据库初始化

### ISSUE THREAD

**Issue by Jddl** [dotnetcore/WTM#189]
项目中注册自定义服务，使用DataContext时，提示没有初始化数据库。
使用下面代码初始化数据库后，Release模式Admin无权限。
`           var configs = app.ApplicationServices.GetRequiredService<Configs>();
            var gd = app.ApplicationServices.GetRequiredService<GlobalData>();
            var test = app.ApplicationServices.GetService<ISpaStaticFileProvider>();
            var cs = configs.ConnectionStrings.Select(x => x.Value);
            foreach (var item in cs)
            {
                var dc = (IDataContext)gd.DataContextCI.Invoke(new object[] { item, configs.DbType });
                dc.DataInit(gd.AllModule, test != null).Wait();
            }`
如何在自定义服务中初始化数据库，或者判断数据库已经初始化。

**Comment by liuliang-wt** [comment]
框架会在第一次访问某个地址的时候检查数据库，如果没有库会初始化一个新库。你所说的自定义服务是什么？

**Comment by Jddl** [comment]
就是用  WebHost.CreateDefaultBuilder(args).ConfigureServices()
添加自己的Service，自定义的Service可能在没有初始化新库的时候使用DataContext。
怎么知道库已经初始化好

**Comment by liuliang-wt** [comment]
这个可能实现不了，框架初始化的时候需要做很多工作才能初始化数据库里的数据，而有的信息要直到第一次发生实际访问的时候才能获取到。看看你能不能换个思路，不在注册服务的时候就访问数据库，而是在后面controller里使用这个服务的时候再使用DC

**Comment by Jddl** [comment]
增加以下代码即可，建议DataContext或者全局变量中增加是否初始化库的属性

` ` ` 
app.Use(async (context, next) =>
            {
                if (InitDataBase == false)
                {
                    var lg = app.ApplicationServices.GetRequiredService<LinkGenerator>();
                    foreach (var m in gd.AllModule)
                    {
                        //if (m.IsApi == true)
                        //{
                        foreach (var a in m.Actions)
                        {
                            var u = lg.GetPathByAction(a.MethodName, m.ClassName, new { area = m.Area?.AreaName });
                            if (u == null)
                            {
                                u = lg.GetPathByAction(a.MethodName, m.ClassName, new { id = 0, area = m.Area?.AreaName });
                            }
                            if (u != null && u.EndsWith("/0"))
                            {
                                u = u.Substring(0, u.Length - 2);
                                u = u + "/{id}";
                            }
                            a.Url = u;
                        }
                        //}
                    }

                    var test = app.ApplicationServices.GetService<ISpaStaticFileProvider>();
                    var cs = configs.ConnectionStrings.Select(x => x.Value);
                    foreach (var item in cs)
                    {
                        var dc = (IDataContext)gd.DataContextCI.Invoke(new object[] { item, configs.DbType });
                        dc.DataInit(gd.AllModule, test != null).Wait();
                    }
                    GlobalServices.SetServiceProvider(app.ApplicationServices);
                    InitDataBase = true;
                }

                if (context.Request.Path == "/")
                {
                    context.Response.Cookies.Append("pagemode", configs.PageMode.ToString());
                    context.Response.Cookies.Append("tabmode", configs.TabMode.ToString());
                }
                await next.Invoke();
                if (context.Response.StatusCode == 404)
                {
                    await context.Response.WriteAsync(string.Empty);
                }
            });

` ` `

**Comment by liuliang-wt** [comment]
你这是把源码又复制了一遍啊，可是你这样写他也会等到第一次有实际访问的时候才初始化数据库啊。。。

**Comment by Jddl** [comment]
好像是有点问题的

**Comment by Jddl** [comment]
```  
while (!_context.Database.CanConnect())
{
                    await Task.Delay(TimeSpan.FromSeconds(3));
}
```
这样也是可以的。
多谢回复，已赞赏！
