### ISSUE TITLE
[Bug]前后端分离React版本，表单中下拉列表、复选列表数据引用另外一张表的字段时，初始值不正确

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#19]
1、环境
数据库：PostgreSQL
前后端分离React版本
github上拉的WTM代码，执行里面的WalkingTec.Mvvm.ApiDemo项目
2、执行步骤
1）对Major、Student、School模型依次生成专业管理、学生管理、学校管理的CRUD前后端代码；
2）增加一条学校信息：北京大学，如下图
<img width="1155" alt="屏幕快照 2019-04-30 10 35 46" src="https://user-images.githubusercontent.com/9619081/56938777-af011300-6b36-11e9-8047-0e83273056e5.png">

3）增加一条学生信息：张三
<img width="1158" alt="屏幕快照 2019-04-30 10 44 52" src="https://user-images.githubusercontent.com/9619081/56938781-b9bba800-6b36-11e9-8b39-cdf858fd97ae.png">

4）问题：进入专业管理，新增专业，表单中所属学校下拉列表、学生复选框没有显示2）、3）步增加的学校、学生，如下图
<img width="1152" alt="屏幕快照 2019-04-30 10 36 08" src="https://user-images.githubusercontent.com/9619081/56938854-1919b800-6b37-11e9-84cf-cd65bb76cd49.png">

5）退出前后台程序重新启动运行前后台后，进入专业管理，新增专业，表单中所属学校下拉列表、学生复选框正常显示了之前添加的学生，但是学校还是显示不出来，如下图：

<img width="1144" alt="屏幕快照 2019-04-30 11 05 15" src="https://user-images.githubusercontent.com/9619081/56939052-8e39bd00-6b38-11e9-991c-a9cc36021bec.png">

**Comment by liuliang-wt** [comment]
@liaoyongxiong 
1. 新生成的后台代码需要重新启动后台才能生效
2. apidemo中的program.cs里定义了学校需要数据权限，所以你这里显示不出来已经添加的数据。你可以在系统管理中的数据权限页面给学校分配数据权限
