### ISSUE TITLE
有关使用EFCore命令更新数据库时出现错误的问题

### ISSUE THREAD

**Issue by punisherCN** [dotnetcore/WTM#190]
在使用EFCore命令更新修改的类到数据库时，出现了一个错误，提示  数据库中已存在名为 'ActionLogs' 的对象，更新失败。新手不明就里，这里再请教一下，谢谢。

**Comment by liuliang-wt** [comment]
使用efcore的migrate命令的时候就不要先运行代码，因为你运行了代码就已经生成数据库了而这时候并没有migration的记录，应该先使用add migration 和 update 来生成数据库，这样你migration的信息和数据库是同步的。 你现在可以把数据库删掉，然后运行 add migration 和 update， 以后再修改类之后再add migration和update，这样就一直是同步的了

**Comment by punisherCN** [comment]
按照您的说法，我把数据库删除了。但在运行 add migration时，提示：No migrations configuration type was found in the assembly 'PMTMS.DataAccess'. (In Visual Studio you can use the Enable-Migrations command from Package Manager Console to add a migrations configuration).是缺少配置文件或者什么的吗？

**Comment by punisherCN** [comment]
感谢您的回答，原来是我这里EF和EFCore同时存在的原因。使用EntityFrameworkCore\Add-Migration这样的命令格式就没有问题了，感谢您的回答。
