### ISSUE TITLE
使用2.x最新版本发布系统时选择独立模式出现包降级问题

### ISSUE THREAD

**Issue by haoxiangxiang** [dotnetcore/WTM#191]
如题 

我使用的是2.x版本的最新版 ，在发布系统 时，考虑到不再安装.netcore相关依赖环境，在vs里选择了“独立”模式，但发布时报错
“检测到包降级 2.26降级到2.24”

![1](https://user-images.githubusercontent.com/29137687/71232784-49180480-232e-11ea-80ea-187995a29b01.png)

**Comment by liuliang-wt** [comment]
这是因为生成项目得时候错误得加入了一个重复的包 Microsoft.EntityFrameworkCore.Design，下个版本会修复，目前你删了这个包就好了


![无标题10](https://user-images.githubusercontent.com/15852860/71234706-c777a500-2334-11ea-9a2a-13b46f8f1fd7.png)
