### ISSUE TITLE
自定义下载如何实现

### ISSUE THREAD

**Issue by w452844226** [dotnetcore/WTM#192]
我想在操作列添加一个自定义的下载按钮，该如何实现？
我尝试了一下好像不行

**Comment by liuliang-wt** [comment]
目前框架列表中的按钮没有下载文件的类型，这个后续版本会增加。
目前你可以使用SetOnClickScript方法，让按钮调用页面上的一段js，然后让那段js实现下载。
比如，我在学校管理ListVM里这样添加一个按钮：

this.MakeAction("School","Download","测试下载",null, GridActionParameterTypesEnum.NoId).SetShowInRow(true).SetOnClickScript("download"),

然后，在Index页面里加入一个叫download的js方法
<script>
  function download() {
    var form = $('<form method="POST" action="/school/download">');
    $('body').append(form);
    form.submit();
    form.remove();

  }
</script>

这样，点按钮的时候就会调用页面上的这个download方法，而这个方法里模拟了一个表单提交到/school/download地址，/school/download 方法直接返回文件即可，类似这样：
 public IActionResult Download()
        {
            return File(new byte[0], "application/vnd.ms-excel", $"test.xls");
        }

**Comment by w452844226** [comment]
这种情况下好像无法获取当前行的ID




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuliang-wt"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午5:11
收件人:&nbsp;"dotnetcore/WTM"<WTM@noreply.github.com&gt;;
抄送:&nbsp;"sky"<w452844226@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/WTM] 自定义下载如何实现 (#192)




目前框架列表中的按钮没有下载文件的类型，这个后续版本会增加。
 目前你可以使用SetOnClickScript方法，让按钮调用页面上的一段js，然后让那段js实现下载。
 比如，我在学校管理ListVM里这样添加一个按钮：
 
this.MakeAction("School","Download","测试下载",null, GridActionParameterTypesEnum.NoId).SetShowInRow(true).SetOnClickScript("download"),
 
然后，在Index页面里加入一个叫download的js方法
 <script&gt;   function download() {     var form = $('');     $('body').append(form);     form.submit();     form.remove();   } </script&gt; 
这样，点按钮的时候就会调用页面上的这个download方法，而这个方法里模拟了一个表单提交到/school/download地址，/school/download 方法直接返回文件即可，类似这样：
 public IActionResult Download()
 {
 return File(new byte[0], "application/vnd.ms-excel", $"test.xls");
 }

**Comment by liuliang-wt** [comment]
你同样需要在js里获取当前grid勾选的id，框架提供了一个js方法 ff.GetSelections('gridid'); 你可以在grid上指定一个id，然后通过ff.GetSelections('gridid'); 方法获取

**Comment by w452844226** [comment]
如果是当前行呢，因为按钮是行内按钮，如果是toolbar上面的可以，但是这样操作稍微麻烦点，还有一个问题就是，希望在onclickscript里，传参数，目前是不支持的 ------------------ 原始邮件 ------------------
发件人: "liuliang-wt"<notifications@github.com>
发送时间: 2019年12月20日(星期五) 晚上9:58
收件人: "dotnetcore/WTM"<WTM@noreply.github.com>;
抄送: "w452844226"<w452844226@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dotnetcore/WTM] 自定义下载如何实现 (#192)



你同样需要在js里获取当前grid勾选的id，框架提供了一个js方法 ff.GetSelections('gridid'); 你可以在grid上指定一个id，然后通过ff.GetSelections('gridid'); 方法获取
 
&mdash;

**Comment by liuliang-wt** [comment]
是的，我们下一版会把下载类型的按钮加上，并给onclickscript增加默认参数

**Comment by w452844226** [comment]
期待，期待☺☺ ------------------ 原始邮件 ------------------
发件人: "liuliang-wt"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 凌晨0:17
收件人: "dotnetcore/WTM"<WTM@noreply.github.com>;
抄送: "w452844226"<w452844226@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dotnetcore/WTM] 自定义下载如何实现 (#192)



是的，我们下一版会把下载类型的按钮加上，并给onclickscript增加默认参数
 
&mdash;
