### ISSUE TITLE
关于表关联的问题

### ISSUE THREAD

**Issue by punisherCN** [dotnetcore/WTM#194]
不知道这么问是不是合适，先谢过。比如我有2个表，一个是仪器信息，一个是人员信息，我想做第三个表，相当于仪器出库入库了，其中有仪器的编号、人员的名称以及出入库时间，这里是不是可以不用那个中间表？

**Comment by liuliang-wt** [comment]
你这个第三个表就是多对多的中间表啊，只不过除了关联仪器表和人员表之外还有其他一些入库时间之类的字段
