### ISSUE TITLE
combobox选择一个项后，如何联动改变一个textbox的值? 

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#195]
winform 有事件。这个怎么弄？ 求赐教。。哭

**Comment by liuliang-wt** [comment]
<wt:combobox> 可以指定change-func，指向页面中的一个js方法，然后你在那个js方法中给textbox赋值。 如果以前是弄winform的，那最好先看看asp.net mvc的教程，了解一下基本的bs结构的方法

**Comment by vthe** [comment]
有类似实现的demo吗？ 赶鸭子上架，急着出结果。。谢谢啊、

**Comment by liuliang-wt** [comment]
https://github.com/dotnetcore/WTM/blob/develop/src/WalkingTec.Mvvm.Mvc.Admin/Areas/_Admin/Views/FrameworkMenu/Create.cshtml  源码中的添加菜单部分有类似的功能，你可以参考

**Comment by vthe** [comment]
3q
