### ISSUE TITLE
Controller里的DC和VM里DC有何联系和区别呢？

### ISSUE THREAD

**Issue by hanshuhe** [dotnetcore/WTM#196]
Controller里的DC和VM里DC有何联系和区别呢？在Controller调用DC.Set<School>()和VM里的DC.Set<School>()功能不一样呀，比如VM里的DC.Set<School>().ToList方法可以用，而Controller里的DC.Set<School>()没有ToList方法；

**Comment by liuliang-wt** [comment]
Controller和VM里的DC是完全一样的， VM中的DC实际上是在使用CreateVM方法的时候从Controller传递过去的。 之所以Controller里DC没有ToList方法，应该是Controller里默认没有using System.Linq , ToList这些都是扩展函数，在System.Linq中
