### ISSUE TITLE
添加列表动作按钮失败

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#197]
我尝试自定义一个列表动作按钮，按照说明文件操作可以在列表上方显示，但是在列表操作列上显示有问题无法工作（显示为...且点击无效）
<img width="818" alt="201912212209001" src="https://user-images.githubusercontent.com/52045796/71309079-a56a4980-243e-11ea-8fb1-c627726430d2.png">
> `this.MakeAction("BookVendor","ImportInv","库存导入","库存导入",GridActionParameterTypesEnum.SingleId).SetShowInRow(true)`

**Comment by zxj2433** [comment]
列表上的按钮也可以执行，就是无法放到列表内

**Comment by liuliang-wt** [comment]
嗯，现在layui里面如果某列显示不下，点省略号弹出层里的按钮点不了，你可以把操作列设置的宽一些就好了。
在 InitGridHeader() 方法中，比如这样： this.MakeGridHeaderAction(width: 500)

**Comment by zxj2433** [comment]
谢谢，没想到是列宽的问题......
