### ISSUE TITLE
无法连接sqlserver2012

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#198]
生成代码后，更新ConnectionStrings为

>"ConnectionStrings": [
    {
      "Key": "default",
      //"Value": "Server=(localdb)\\mssqllocaldb;Database=DCMS_db;Trusted_Connection=True;"
      "Value": "Server=10.66.148.88;Database=DCMS;User Id=sauser;Password=sauser;"
    }
  ],
  "DBType": "SqlServer", //使用的数据库，可选mysql,sqlserver,pgsql,sqlite,oracle
  "IsOldSqlServer":false,//如果使用sql server2008或者更老的，请设置为true

> 但是F5执行后总是提示HTTP ERROR 500，换成其他数据库就可以......但是我使用其他的项目连接sqlserver又可以正常用.....是我ConnectString写法的问题么？

**Comment by liuliang-wt** [comment]
User id可能EF无法识别，你换成uid试试。 另外你注意启动时候vs输出里面的错误信息，他如果不能创建数据库，会有具体的错误信息的

**Comment by zxj2433** [comment]
非字符串问题，是有一个类没有定义key，查看vs输出的错误信息后解决了，感谢！
