### ISSUE TITLE
请问业务逻辑应该写在VM里还是写在Controller里？有没有一个指导性的原则？

### ISSUE THREAD

**Issue by nluyan** [dotnetcore/WTM#199]
哪些逻辑应该写在VM，哪些应该是在Controller里？
另外，框架非常好，谢谢！

**Comment by zxj2433** [comment]
我如果说评感觉是不是显的特不专业!哈哈😄，我就是

**Comment by liuliang-wt** [comment]
基本上所有的业务逻辑都应该写在VM中，controller中应该只是简单的调用VM中的逻辑并返回view
