### ISSUE TITLE
菜单的某一目录下，其他的子菜单都没有权限，但是这个空目录还是在显示，而且点击后404？

### ISSUE THREAD

**Issue by soundsun** [dotnetcore/WTM#202]
能否让这个空目录不显示

**Comment by liuliang-wt** [comment]
空目录系统肯定是不显示的，而且如果是目录你点击也是没用的，所以请检查一下你点击404的那个确定配置成了一个目录？

**Comment by liuliang-wt** [comment]
sorry，我看了一下，如果是三级的菜单会出现这个bug，我们会在下一版修复

@alienwow 你改一下，现象是空目录下面如果还是一个空目录，系统没有过滤掉
