### ISSUE TITLE
我想在选过商品下拉框后展示出商品的另一个属性在网页面上

### ISSUE THREAD

**Issue by haoxiangxiang** [dotnetcore/WTM#203]
我的商品表里有设备名称，设备配件信息 等 字段。
在页面上，新建设备安装记录时，我在下拉框里根据设备名称选过设备后，如何将该设备对应的设备配件信息字段也一块展示在网页的txtbox中，一个设备名称对应一个设备配件信息。

**Comment by liuliang-wt** [comment]
参考 #195
