### ISSUE TITLE
编辑页面绑定列表Grid模型输出错误

### ISSUE THREAD

**Issue by lwq202** [dotnetcore/WTM#204]
![JVV%7U}6%5LOA06DWUV}PHG](https://user-images.githubusercontent.com/47727942/71400271-27d25380-2661-11ea-8d5b-2360df20f979.png)
![JVV%7U}6%5LOA06DWUV}PHG](https://user-images.githubusercontent.com/47727942/71400278-2f91f800-2661-11ea-898b-e541fd28c09b.png)
这个在模型中嵌套子表的时候出现问题，如果是编辑列表的话没有问题，如果是查看列表就会出现这个问题，生成的隐藏id被生成到 第一列的标签里面了

**Comment by liuliang-wt** [comment]
请提供一个最简单的场景让我们能复现，比如某个正常的列表，在什么情况下会出现你说的问题
