### ISSUE TITLE
我用SqlServer2008R2的数据库，设置了IsOldSqlServer为true，但运行时报错

### ISSUE THREAD

**Issue by alexywt** [dotnetcore/WTM#208]
报错内容：
Microsoft.Data.SqlClient.SqlException:“'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。”

**Comment by hanshuhe** [comment]
你选的版本是netcore2.2就可以了，根据亮总解释说netcore3.0不支持sql2008了

**Comment by liuliang-wt** [comment]
是的，3.x版本的框架使用的是.netcore 3.0和ef3.0，目前EF3.0不支持sql 2008了。
你如果用2.x版本的框架是可以的
