### ISSUE TITLE
设置只读字段后在Grid里只能显示为0

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#210]
亮哥您好，我在model中设置了一个只读的属性，但是在grid查看中全部显示为0，请问是需要改动哪的配置还是当前框架就这样？
![image](https://user-images.githubusercontent.com/52045796/71447811-5ab63d80-276e-11ea-97b7-febc19864723.png)
![image](https://user-images.githubusercontent.com/52045796/71447818-73265800-276e-11ea-8f77-dfb1e423fdd1.png)

**Comment by liuliang-wt** [comment]
你这么写应该是没问题，问题是你看看你ListVM中的查询语句有没有Select InvQty和OrderQty这两个字段，如果没有选，那他们就是0，减完了也是0

**Comment by zxj2433** [comment]
> 你这么写应该是没问题，问题是你看看你ListVM中的查询语句有没有Select InvQty和OrderQty这两个字段，如果没有选，那他们就是0，减完了也是0

哦，好的，谢谢！
