### ISSUE TITLE
在详细画面中，显示子表的grid数据，如何处理？

### ISSUE THREAD

**Issue by soundsun** [dotnetcore/WTM#213]

**Comment by liuliang-wt** [comment]
原理是一样的，你可以在详细画面绑定的VM中添加一个ListVM的属性，然后在页面中添加grid绑定到那个ListVM的属性上。 唯一需要注意的是，如果你直接new那个ListVM，你需要在原VM上调用CopyContext把原vm的DC，Session等属性传递给ListVM
