### ISSUE TITLE
导出excel，有隐藏列如何导出

### ISSUE THREAD

**Issue by zxp6499** [dotnetcore/WTM#216]
InitGridHeader()里有隐藏列
也重写了GetExportQuery()，查询算有列，但导出时隐藏列还是导不出来。

**Comment by zxp6499** [comment]
把源码里RemoveActionAndIdColumn 关于隐藏列的处理删了就能导了

**Comment by liuliang-wt** [comment]
隐藏列本身不导出是框架的设计
你在InitGridHeader方法中可以根据SearcherMode变量来判断当前是导出还是搜索，从而设置不同的列。

**Comment by zxp6499** [comment]
好的，谢谢
