### ISSUE TITLE
关闭生成代码时出现异常

### ISSUE THREAD

**Issue by Newxml** [dotnetcore/WTM#218]
core2.2版本

![image](https://user-images.githubusercontent.com/34527830/71552856-45c3fd80-2a3f-11ea-9160-a9742a65eacd.png)

![image](https://user-images.githubusercontent.com/34527830/71552859-5d02eb00-2a3f-11ea-8300-d73c08a61dd5.png)

在后面几步点关闭同样会出现该问题

**Comment by zxj2433** [comment]
手机看不了图片，不过应该是model写的问题，我们这用的都正常

**Comment by Newxml** [comment]
> 手机看不了图片，不过应该是model写的问题，我们这用的都正常

我点的是关闭按钮，为什么会抛异常？

**Comment by liuliang-wt** [comment]
这好像是个bug，稍后我修改一下，不过倒是不影响使用
