### ISSUE TITLE
业务需求，生成代码使用自定义名称。不使用数据库表名称

### ISSUE THREAD

**Issue by Newxml** [dotnetcore/WTM#219]
Core 2.2版本
![image](https://user-images.githubusercontent.com/34527830/71552876-9e939600-2a3f-11ea-8d56-f33b42e4bb2c.png)
生成代码使用自定义名称,不使用数据库表名称

**Comment by zxj2433** [comment]
[column(name="")]

文档里有，自定义主键那

**Comment by Newxml** [comment]
> [column(name="")]
> 
> 文档里有，自定义主键那

我要生成代码的时候自定义控制器视图及VM名称与[column(name="")] 并没有什么关系吧？ column不是改字段名称吗？

**Comment by zxj2433** [comment]
表名和类名可以不一样啊，ef支持的
datacontext 中 dbset<类名> 表名

**Comment by Newxml** [comment]
> 表名和类名可以不一样啊，ef支持的
> datacontext 中 dbset<类名> 表名

OK
