### ISSUE TITLE
[Bug]前后端分离React版本，批量导出时枚举型的字段导出值不正确

### ISSUE THREAD

**Issue by liaoyongxiong** [dotnetcore/WTM#22]
【版本】：前后端分离React版本
【预置条件】
模型中有枚举字段，添加记录时，设置了枚举字段的值
【问题】批量导出时，枚举字段的值为空（导出不正确）
如下：
1、记录信息
<img width="932" alt="屏幕快照 2019-05-17 00 03 17" src="https://user-images.githubusercontent.com/9619081/57869698-2d003200-7838-11e9-9592-c266254a0ca7.png">
导出记录：
<img width="1085" alt="屏幕快照 2019-05-17 00 03 52" src="https://user-images.githubusercontent.com/9619081/57869749-47d2a680-7838-11e9-8990-49c63dc36bdf.png">
枚举类型的字段，导出的值都为空了。

**Comment by liuliang-wt** [comment]
感谢提出问题，确实是系统bug，已经修复。下个版本发布时候升级即可。
