### ISSUE TITLE
点击<wt:image />控件，如何弹出预览窗口，及放大缩小？

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#220]
![image](https://user-images.githubusercontent.com/10944353/71572251-1da8cd00-2b19-11ea-942d-4fd0624b53bf.png)
如图，点击照片，如何弹出预览窗口，弹出后的照片如何放大缩小移动？

**Comment by liuliang-wt** [comment]
代码生成器默认应该会给你生成下载和预览两个按钮，预览按钮就是弹出窗口

**Comment by ChiLoneYu** [comment]
目前 word pdf 如何在线预览？ @liuliang-wt
