### ISSUE TITLE
请教关于如何在首页显示数据库内数据的问题

### ISSUE THREAD

**Issue by liuxiangyu95** [dotnetcore/WTM#223]
请问各位大神，WTM框架如何将主页的模拟数据转换为数据库内真实的数据，可以的话请用第一个模块作为例子讲一下如何实现谢谢了

**Comment by liuliang-wt** [comment]
首页上的报表使用的是echart，基本上都是echart的写法，你可以参考/views/home/frontpage.cshtml文件最下方的那些js，区别就是frontpage里数据是写死的假数据，你应该用ajax调用后台接口返回一些真实数据
