### ISSUE TITLE
React模板生成后无法运行

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#224]
生成后模板后，在VS中生成失败
![image](https://user-images.githubusercontent.com/52045796/71588544-db08e400-2b5c-11ea-8a68-614c4ba6e692.png)

提示要安装node.js,可是安装后重启VS也不管用
![image](https://user-images.githubusercontent.com/52045796/71588558-e52ae280-2b5c-11ea-8c80-6e47dcde40f2.png)

**Comment by zxj2433** [comment]
![无标题](https://user-images.githubusercontent.com/52045796/71588610-173c4480-2b5d-11ea-920d-4f0192bf2bcb.png)

**Comment by liuliang-wt** [comment]
需要node 10.0 以上，去官网下载就行
