### ISSUE TITLE
关于怎么调试框架代码？

### ISSUE THREAD

**Issue by Herryzzz** [dotnetcore/WTM#225]
请问下，怎么用调试框架代码？ 是直接用框架源码生成的dll替换掉nuget里面的dll?  还是 删除nuget引用直接本地引入dll? 求指点一下

**Comment by liuliang-wt** [comment]
你可以把源码下载下来，把src里面的几个项目添加到你的项目里，然后把nuget里面引用的WalkingTec.xxx的包删除，替换成同名的项目就可以了

**Comment by Herryzzz** [comment]
好的，谢谢，亮哥幸苦。
