### ISSUE TITLE
自己做了一个薪酬查询的模块，但是菜单管理中看不到这个模块，角色管理中也分配不到这个模块

### ISSUE THREAD

**Issue by hanshuhe** [dotnetcore/WTM#226]
如题

**Comment by liuliang-wt** [comment]
你继承BaseController了么？

**Comment by hanshuhe** [comment]
亮总，继承了，代码自动生成的，我还没有改任何东西。我查了一下代码，也是继承了。 public partial class SalaryController : BaseController

**Comment by liuliang-wt** [comment]
那不应该，你在调试模式下，左侧菜单有你新加的这个模块么？

________________________________
发件人: hanshuhe <notifications@github.com>
发送时间: Wednesday, January 1, 2020 8:26:15 AM
收件人: dotnetcore/WTM <WTM@noreply.github.com>
抄送: liuliang-wt <liuliang79@live.com>; Comment <comment@noreply.github.com>
主题: Re: [dotnetcore/WTM] 自己做了一个薪酬查询的模块，但是菜单管理中看不到这个模块，角色管理中也分配不到这个模块 (#226)


亮总，继承了，代码自动生成的，我还没有改任何东西。我查了一下代码，也是继承了。 public partial class SalaryController : BaseController

―

**Comment by hanshuhe** [comment]
亮总，有的，调试的时候左侧有这个菜单，功能可以使用，就是在给角色分配权限的时候，找不到这个菜单

**Comment by liuliang-wt** [comment]
你需要先在菜单管理中添加这个模块，然后才能在角色管理中给这个菜单项配置权限。

你在菜单管理中添加一个新菜单项的时候，在模块的下拉列表中也找不到这个模块么？
