### ISSUE TITLE
修改没有同步

### ISSUE THREAD

**Issue by Jddl** [dotnetcore/WTM#227]
我重写了DoEdit方法，代码如下。页面上修改成功了，但刷新后又还原了。调用时使用了DoEdit(true)
        public override void DoEdit(bool updateAllFields = false)
        {
            Entity.SyncStatus = SyncStatus.SyncUpdate;
            base.DoEdit(updateAllFields);
        }

**Comment by liuliang-wt** [comment]
参考 #178

**Comment by Jddl** [comment]
vm.FC.Add("Entity.jcry", 1);
vm.FC.Add("Entity.jcsj", 1);
按照这样的写法没问题。
如果是批量修改，怎么写呢？

**Comment by liuliang-wt** [comment]
批量修改框架提供了BatchVM，你可以在代码生成器里面勾选一些批量修改的字段试试

**Comment by Jddl** [comment]
我的意思是在代码里修改，不是界面上(View)

**Comment by Jddl** [comment]
目前我是重写DoBatchEdit方法，把Ids都遍历一下，就是不知道有没有更简洁的写法
        public override bool DoBatchEdit()
        {
            var ret = base.DoBatchEdit();
            foreach (var id in Ids)
            {
               var user = DC.Set<AccessUser>().FirstOrDefault(x => x.ID.ToString() == id);
               if (user!=null)
               {
                   user.SyncStatus = SyncStatus.SyncUpdate;
                   DC.Set<AccessUser>().Update(user);
               }
            }
            DC.SaveChanges();
            return ret;
        }

**Comment by liuliang-wt** [comment]
BatchVM中包括了一个LinkedVM来保存你要修改的字段，你在LinkedVM中定义一个也叫SyncStatus的变量，然后给LinkedVM.SyncStatus赋值，并且给FC中加入LinkedVM.SyncStatus，模拟这是前台提交的字段。
这样就可以了，不需要重写DoBatchEdit

**Comment by Jddl** [comment]
```
vm.LinkedVM.SyncStatus = SyncStatus.SyncUpdate;
vm.FC.Add("LinkedVM.SyncStatus", 1);
```
这样还是不行啊

**Comment by liuliang-wt** [comment]
Sorry，DoBatchEdit逻辑判断有点问题，我一会修改一下，下一版就好了，目前你可以这样绕过这个bug：

vm.FC["LinkedVM.SyncStatus"] = new StringValues("1");

**Comment by Jddl** [comment]
good
