### ISSUE TITLE
grid使用sm尺寸时，生成的前端样式高度错位

### ISSUE THREAD

**Issue by mylidong** [dotnetcore/WTM#231]

**Comment by liuliang-wt** [comment]
能具体描述一下么，截图之类的

**Comment by mylidong** [comment]
![Uploading 无标题.png…]()

**Comment by mylidong** [comment]
![无标题](https://user-images.githubusercontent.com/57850334/71864618-3c234f80-313b-11ea-90fb-4c59fd2e7ca4.png)

**Comment by mylidong** [comment]
> 能具体描述一下么，截图之类的


![](https://user-images.githubusercontent.com/57850334/71864618-3c234f80-313b-11ea-90fb-4c59fd2e7ca4.png)
