### ISSUE TITLE
CRUDVM里DC是null值，且CreateDC也获取不到

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#233]
在CRUDVM里无法使用DC么?
![image](https://user-images.githubusercontent.com/52045796/71783488-6cc39600-3022-11ea-9609-7a32a0995639.png)

**Comment by liuliang-wt** [comment]
VM应该在controller中使用CreateVM方法来新建vm，这样可以把DC，LoginUserInfo这些数据传给vm。
你在VM中使用CreateDC是肯定可以创建DC的，你这个报错有可能是LoginUserInfo为空，LoginUserInfo记录的是当前登陆用户的信息
