### ISSUE TITLE
给作者的建议

### ISSUE THREAD

**Issue by lisuyan0** [dotnetcore/WTM#238]
1.既然框架不错 ，建议出一个视频教程（付费） 放到腾讯公开课

2.视频教程 详细介绍一个完整 小系统开发过程 或者一个模块的开发过程

3.这样既可以 增加群主的收入 ，也可以壮大框架使用者数量 

4.这样一来框架才会有不断生命力，如果大部分人一知半解  用着用着也会放弃

5.强烈建议在后期的框架中  加入 工作流  哪怕是状态机也好

**Comment by dl1024** [comment]
我的观点也是这样的。。希望WTM早日出付费的精品教程。。
