### ISSUE TITLE
WTM LAYUI 版功能修改建议

### ISSUE THREAD

**Issue by feelhum** [dotnetcore/WTM#24]
1、	数据权限->新建数据权限->选择用户组
       建议修改成弹窗，选择用户组，切弹出可以搜索，且能分页
2、数据权限->修改数据权限->选择用户组
        建议修改成弹窗，选择用户组，切弹出可以搜索，且能分页
3、	数据权限->新建数据权限->选择数据权限
建议弹出的数据权限清单，增加按Name搜索的功能，且能分页
4、	数据权限->修改数据权限->选择数据权限
建议弹出的数据权限清单，增加按Name搜索的功能，且能分页
5、用户组管理->数据权限
  如果有多个数据权限的情况下，多个必须都填写，不能只填写其中一种数据权限

**Comment by zangxx66** [comment]
我也提一个，管理员在给自己编辑菜单管理时，刷新页面并不会生效，需要重新登录
