### ISSUE TITLE
单行数量为啥没有5  five ？ 有什么典故吗？

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#240]
![QQ截图20200108112007](https://user-images.githubusercontent.com/10944353/71947815-fd5bcb00-3208-11ea-9366-bbbb3441f177.jpg)

namespace WalkingTec.Mvvm.TagHelpers.LayUI
{
    public enum ItemsPerRowEnum
    {
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4,
        Six = 6,
        Twelve = 12
    }
}

**Comment by nluyan** [comment]
必须是可以被12整除吧

**Comment by liuliang-wt** [comment]
@nluyan 正解
