### ISSUE TITLE
在mac上打开在线生成的zip包除了首页，其它都运行不了

### ISSUE THREAD

**Issue by xiaoyu5062** [dotnetcore/WTM#241]
![image](https://user-images.githubusercontent.com/7548606/71959306-66553a00-322d-11ea-9efd-0e3e5a42ab5b.png)
.net core 3.1   mysql 5.7

**Comment by xiaoyu5062** [comment]
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched: /Areas/_Admin/Views/ActionLog/Index.zh.cshtml /Areas/_Admin/Views/ActionLog/Index.cshtml /Areas/_Admin/Views/Shared/Index.zh.cshtml /Areas/_Admin/Views/Shared/Index.cshtml /Views/Shared/Index.zh.cshtml /Views/Shared/Index.cshtml /Pages/Shared/Index.zh.cshtml /Pages/Shared/Index.cshtml at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations) at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by liuliang-wt** [comment]
这是因为他找不到编译在admin dll里的页面，这种情况在windows上没有出现过，不能确定是否是mac上visual studio的问题。

@alienwow 你试一下

**Comment by alienwow** [comment]
![image](https://user-images.githubusercontent.com/5558670/71980145-56a01a80-325a-11ea-9567-756da548f681.png)
![image](https://user-images.githubusercontent.com/5558670/71980227-84855f00-325a-11ea-8227-d4e2ed279817.png)

**Comment by xiaoyu5062** [comment]
@alienwow 我这边选的按项目去生成
![image](https://user-images.githubusercontent.com/7548606/72032740-48d6ad80-32cb-11ea-8c56-92d3161c440e.png)
![image](https://user-images.githubusercontent.com/7548606/72032882-ad920800-32cb-11ea-8e76-bf01a5a658aa.png)

**Comment by alienwow** [comment]
这边已经复现该问题。

现有如下解决方案：
1. vs for mac下清理一下解决方案/项目，然后重新运行
1. 使用vscode进行开发

**Comment by xiaoyu5062** [comment]
恩，清理解决方案后正常运行
