### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by KINGGUOKUN** [dotnetcore/WTM#245]
请问多系统SSO，权限划分这块儿，目前支持吗？从设计来看，JWT、Cookie做SSO应该是可以，那各子系统的侧边菜单、权限控制怎么个弄法儿？

**Comment by liuliang-wt** [comment]
目前其实可以在主系统中维护所有用户，角色和菜单，通过在菜单管理中配置 "/aaa/bbb"这种形式的外部地址来代表各自主系统内的地址， 其他系统登陆时调用主系统的登陆接口和获取菜单的接口即可

**Comment by KINGGUOKUN** [comment]
嗯，我也是这么想的，获取菜单是可扩展的吗？
