### ISSUE TITLE
更新时，重复性check不起作用

### ISSUE THREAD

**Issue by soundsun** [dotnetcore/WTM#248]
在vm中写了SetDuplicatedCheck方法，在新增时可以检查出重复数据，但是更新时，把一条数据修改成和数据库中一样的，这个方法没起作用
        public override DuplicatedInfo<ProductOpenDay> SetDuplicatedCheck()
        {
            var rv = CreateFieldsInfo();
            rv.AddGroup(SimpleField(x => x.product_cd), SimpleField(x => x.open_day));
            return rv;
        }

**Comment by liuliang-wt** [comment]
AddGroup里传两个参数意味着 这两个字段的组合不能重复，你是不是更新的时候把一个字段改成了数据库里有的，但是其实他俩的组合在库里并没有一样的？

**Comment by soundsun** [comment]
修改时，画面的这个组合数据，和数据库中某条数据一样的
