### ISSUE TITLE
是我发布的方法不对吗？ 有什么需要注意的地方吗？ 

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#249]
![image](https://user-images.githubusercontent.com/10944353/72231395-2cea4900-35f6-11ea-8468-d3e2c0242825.png)

我按照这个的配置，发布，然后到iis。 
登录页可以出来，点击登录后，就不行了。有用你的原始项目测试，未做任何更改，也是不行。

![image](https://user-images.githubusercontent.com/10944353/72231350-f6143300-35f5-11ea-90e5-079dd66ad780.png)

**Comment by liuliang-wt** [comment]
如果登陆页可以出来，只是点登陆报错，很大可能是你数据库连接字符串配置的不对。原始项目默认使用的是跟随visualstudio一起安装的localdb，你服务器上未必有localdb。 你检查一下appsettings里的连接字符串，改成你服务器的数据库应该就可以了

**Comment by vthe** [comment]
我是部署在本机上的。数据库连接如下： 
Server=.;Database=aaa_db;Trusted_Connection=True;
应该是正确的才对吧？

**Comment by vthe** [comment]
可以了。本机也要用用户名和密码。user id = sa;pwd = abcd.1234;
不能Trusted_Connection=True;
