### ISSUE TITLE
用户管理没法修改角色

### ISSUE THREAD

**Issue by shinercan** [dotnetcore/WTM#25]
角色修改后保存不了

**Comment by shinercan** [comment]
是我自己搞错了

**Comment by shinercan** [comment]
![image](https://user-images.githubusercontent.com/12811673/60594418-7f40e680-9dd7-11e9-9cc1-cc5be697b8de.png)
模型密码为必填项目
![image](https://user-images.githubusercontent.com/12811673/60594478-aa2b3a80-9dd7-11e9-8251-d61720ffde2f.png)
修改界面不存在密码
![image](https://user-images.githubusercontent.com/12811673/60594653-01c9a600-9dd8-11e9-8649-e19d4f214f36.png)
过滤器模型验证不通过，重新加载了VM导致角色选择被旧值覆盖，从而无法保存

**Comment by liuliang-wt** [comment]
非常感谢，这是最近修改其他问题时出现的bug，现已修复。下一版本发布时会更新

**Comment by shinercan** [comment]
幸苦了，深夜为社区耕耘👍
