### ISSUE TITLE
可否修改下框架？验证码的图片不要出现这个绿色的，人眼很难辨识出来。

### ISSUE THREAD

**Issue by vthe** [dotnetcore/WTM#254]
![image](https://user-images.githubusercontent.com/10944353/72418316-8c428780-37b5-11ea-8171-765fbe3ca539.png)

颜色稍微做下加深也可以

**Comment by liuliang-wt** [comment]
可以，不过这个验证码其实只是框架演示登陆的功能，你是可以自己实现的，整个登陆页面和后台方法都是可以修改的
