### ISSUE TITLE
怎么隐藏操作列

### ISSUE THREAD

**Issue by 516018579** [dotnetcore/WTM#263]
我想要一个只读的列表,没有任何操作

**Comment by liuliang-wt** [comment]
ListVM中有一个override 的 InitGridAction 函数，是用来指定列表的操作按钮的，你删了就行

**Comment by 516018579** [comment]
删了列还在, 只是按钮没了

![image](https://user-images.githubusercontent.com/8523006/72790751-1fc1ff80-3c71-11ea-944b-6c4a5d744f56.png)

**Comment by liuliang-wt** [comment]
你是说你要删除的是每行最右侧的那个操作列？那个是在 InitGridHeader 函数中，有一个MakeGridHeaderAction，这个是用来添加右侧操作列的，你删了这句就好了
