### ISSUE TITLE
WTM后台服务类使用

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#269]
亮哥，我想在VMs里增加一个类作为后台服务类，但是继承BackgroundService并再ConfigureServices里注入后，不起作用，只能子Model里新建一个类才行，请问WTM有自己的类似BackgroundService的基类么？

**Comment by liuliang-wt** [comment]
WTM里并没有内置BackgroudService，不过你在WTM中自己加BackgroundService应该是没有问题的，你说的不起作用是报错么？

**Comment by zxj2433** [comment]
没有报错，就是不会自动执行，只有在Model里的类才可以执行
![image](https://user-images.githubusercontent.com/52045796/73358359-69e25b00-42d9-11ea-978e-b06fa5448c68.png)

**Comment by zxj2433** [comment]
因为在VMs下面各种操作会方便些，但是现在只能把后台服务写在Model里！

**Comment by liuliang-wt** [comment]
这个好奇怪，我再看看。不过我的习惯是把这个类写在主项目里。。。
