### ISSUE TITLE
自定义下载功能显示乱码

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#270]
增加一个下载的自定义按钮，根据传入的ID下载指定的listVM，但是现在的写法生成的总是乱码，是哪个地方不对么？
![image](https://user-images.githubusercontent.com/52045796/73452977-06722f00-43a6-11ea-927a-b63545f4c176.png)
![image](https://user-images.githubusercontent.com/52045796/73452989-0eca6a00-43a6-11ea-8700-2f8520f02f86.png)
![image](https://user-images.githubusercontent.com/52045796/73453110-49cc9d80-43a6-11ea-85a8-fed8305d73b9.png)

**Comment by liuliang-wt** [comment]
默认的按钮尝试显示返回的页面，你可以在MakeAction后面用 .SetIsDownload方法来指定这个按钮应该下载一个文件

**Comment by zxj2433** [comment]
> 默认的按钮尝试显示返回的页面，你可以在MakeAction后面用 .SetIsDownload方法来指定这个按钮应该下载一个文件

我可以看过MakeAction没看到SetIsDownload方法，也没有类似Explor字眼的方法。。。

**Comment by liuliang-wt** [comment]
这个是最新的版本加的功能，你升级到最新就有了

**Comment by zxj2433** [comment]
> 这个是最新的版本加的功能，你升级到最新就有了

我现在是2.4.5，需要升到3.x才行么？

**Comment by liuliang-wt** [comment]
2.4.5就可以了啊，没有么？比如：
this.MakeAction("controller","action","test","test", GridActionParameterTypesEnum.NoId,dialogWidth:800).SetIsDownload(),

**Comment by zxj2433** [comment]
> 2.4.5就可以了啊，没有么？比如：
> this.MakeAction("controller","action","test","test", GridActionParameterTypesEnum.NoId,dialogWidth:800).SetIsDownload(),

![image](https://user-images.githubusercontent.com/52045796/73460435-70450580-43b3-11ea-9b7d-dc83e93e566f.png)
我原本是2.4.4，后来用NuGet升级到2.4.5的

**Comment by liuliang-wt** [comment]
呃，我在官网上试了一下，最新生成的项目是可以的，你升级到2.4.5也应该没问题。你尝试删掉bin和obj目录，重新打开vs重现编译一次试试

**Comment by zxj2433** [comment]
删了也不行，好像NuGet的升级有问题，确实还是引用的2.4.4......
![image](https://user-images.githubusercontent.com/52045796/73462297-86a09080-43b6-11ea-884c-dbfecffc31b7.png)

**Comment by zxj2433** [comment]
> 呃，我在官网上试了一下，最新生成的项目是可以的，你升级到2.4.5也应该没问题。你尝试删掉bin和obj目录，重新打开vs重现编译一次试试

升级需要升级两次，一次主项目，还有一次Model.......
现在好了，谢谢亮哥
![image](https://user-images.githubusercontent.com/52045796/73463183-c9af3380-43b7-11ea-9990-3c747ca16517.png)
