### ISSUE TITLE
用户注册问题

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#277]
由于自带的FrameworkUserBase里Password不符合业务的要求，所以我new了一个Password，但是在注册时提示Password为空，调试查看到基类的Password还是空的，而doAdd()里还是调用的基类的值，请问这个怎么解决？
![TIM图片20200207150333](https://user-images.githubusercontent.com/52045796/74011277-637f6d80-49c2-11ea-8f99-fe449af2b7b6.png)
![TIM图片20200207150340](https://user-images.githubusercontent.com/52045796/74011292-6da16c00-49c2-11ea-9e60-59ac694bade6.png)

**Comment by liuliang-wt** [comment]
这样是不行的，因为FrameworkUserBase本身已经生成表了，你自定义用户类可以加字段，但是没办法修改已有字段。你这需求可以在vm层面加一些验证，来验证密码是否符合你的长度要求。
