### ISSUE TITLE
react+antd 版本中，菜单管理有bug 

### ISSUE THREAD

**Issue by iwaitu** [dotnetcore/WTM#278]
按照教程中添加模型后，功能使用正常，但是在发布模式下，需要为新增的模块添加菜单，不过添加菜单时无法读出默认的权限，导致无法添加

**Comment by iwaitu** [comment]
尝试了一下 layui版本，没有这个问题，但是 react+antd 有这个问题

**Comment by liuliang-wt** [comment]
目前代码生成器有个小bug，你看clientapp/src/pages/index.ts文件。 里面生成的controller要用全名，命名空间加逗号，再加controller的名字，下一版会修复，目前可以生成代码之后手动改一下
