### ISSUE TITLE
怎么获取数据表格的每页行数和当前页

### ISSUE THREAD

**Issue by XIO-OIX** [dotnetcore/WTM#280]
BasePagedListVM<TModel, TSearcher>类中属性已弃用
//
// 摘要:
//     每页行数
[Obsolete("弃用，改用 DataTableHelper上的Limit")]
public int RecordsPerPage { get; set; }

DataTableHelper方式如何使用？

**Comment by liuliang-wt** [comment]
Searcher.Page 和 Searcher.Limit 可以获取当前页和每页行数

**Comment by XIO-OIX** [comment]
谢谢回复
