### ISSUE TITLE
Dotnet core 3.1 Razor Page Debug Mode 下改动刷新不生效

### ISSUE THREAD

**Issue by GeekEz** [dotnetcore/WTM#287]
Hi,

查了一下貌似需要引用 Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation

并且需要在 ConfigureServices 方法里面加入 services.AddMvc().AddRazorRuntimeCompilation()

这应该如何处理

谢谢

**Comment by liuliang-wt** [comment]
遵循教程就行 https://docs.microsoft.com/zh-cn/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1

ConfigureServices对应的就是Program.cs文件里的 webBuilder.ConfigureServices
