### ISSUE TITLE
菜单权限修改，重启服务才生效吗？

### ISSUE THREAD

**Issue by XIO-OIX** [dotnetcore/WTM#288]
管理员修改菜单权限后，只有重启服务后才生效，请问框架是这么设定的吗

**Comment by liuliang-wt** [comment]
菜单管理页面有一个刷新菜单按钮，点那个就行。因为菜单是全局缓存的，所以修改了之后需要点刷新菜单刷新一下全局缓存

**Comment by XIO-OIX** [comment]
谢谢反馈，已解决
