### ISSUE TITLE
有没有例子演示如何和现有的 Web API 项目(已有数据库)对接?

### ISSUE THREAD

**Issue by GreatFireWall** [dotnetcore/WTM#289]

**Comment by liuliang-wt** [comment]
如果你想使用wtm对接已有的api，那意义不大，因为wtm的很多封装都是基于自己的数据格式，你的webapi返回的数据格式肯定不一样。 
如果只是在已有数据库上开发新代码，那是没问题的，你只要定义的模型字段跟原有数据库能对上就可以。

**Comment by GreatFireWall** [comment]
明白, 感谢回复.
