### ISSUE TITLE
【请教】新项目编译不通过

### ISSUE THREAD

**Issue by fawdlstty** [dotnetcore/WTM#293]
vs2019最新版，nodejs最新版。输出内容如下：
```
1>------ 已启动生成: 项目: QingjiuServer4.Model, 配置: Debug Any CPU ------
1>QingjiuServer4.Model -> F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4.Model\bin\Debug\netcoreapp3.1\QingjiuServer4.Model.dll
2>------ 已启动生成: 项目: QingjiuServer4.DataAccess, 配置: Debug Any CPU ------
3>------ 已启动生成: 项目: QingjiuServer4.ViewModel, 配置: Debug Any CPU ------
3>QingjiuServer4.ViewModel -> F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4.ViewModel\bin\Debug\netcoreapp3.1\QingjiuServer4.ViewModel.dll
2>QingjiuServer4.DataAccess -> F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4.DataAccess\bin\Debug\netcoreapp3.1\QingjiuServer4.DataAccess.dll
4>------ 已启动生成: 项目: QingjiuServer4, 配置: Debug Any CPU ------
4>QingjiuServer4 -> F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4\bin\Debug\netcoreapp3.1\QingjiuServer4.dll
4>v13.8.0
4>Restoring dependencies using 'npm'. This may take several minutes...
4>npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
4>npm WARN deprecated @types/jest-diff@24.3.0: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.
4>npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
4>npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
4>npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
4>npm ERR! Unexpected end of JSON input while parsing near '....32","@types/jake":"l'
4>
4>npm ERR! A complete log of this run can be found in:
4>npm ERR!     C:\Users\fawdlstty\AppData\Roaming\npm-cache\_logs\2020-02-18T13_03_01_512Z-debug.log
4>F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4\QingjiuServer4.csproj(35,5): error MSB3073: 命令“npm install”已退出，代码为 1。
4>已完成生成项目“QingjiuServer4.csproj”的操作 - 失败。
5>------ 已启动生成: 项目: QingjiuServer4.Test, 配置: Debug Any CPU ------
5>QingjiuServer4.Test -> F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4.Test\bin\Debug\netcoreapp3.1\QingjiuServer4.Test.dll
========== 生成: 成功 4 个，失败 1 个，最新 0 个，跳过 0 个 ==========
```

在那个文件夹内执行cmd效果：
```
F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4\ClientApp>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @types/jest-diff@24.3.0: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '....32","@types/jake":"l'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fawdlstty\AppData\Roaming\npm-cache\_logs\2020-02-18T12_32_20_833Z-debug.log

F:\Backup\08_start_up\_repos\qingjiu\Server\src4\QingjiuServer4\ClientApp>
```

然后有提示错误日志，发现json解析不通过：
```
......
4215 silly pacote version manifest for react-app-rewired@2.1.4 fetched in 2ms
4216 silly resolveWithNewModule react-app-rewired@2.1.4 checking installable status
4217 silly pacote version manifest for mockjs@1.0.0 fetched in 15ms
4218 silly resolveWithNewModule mockjs@1.0.0 checking installable status
4219 silly pacote version manifest for node-sass@4.12.0 fetched in 16ms
4220 silly resolveWithNewModule node-sass@4.12.0 checking installable status
4221 silly pacote version manifest for react-scripts@3.2.0 fetched in 6ms
4222 silly resolveWithNewModule react-scripts@3.2.0 checking installable status
4223 silly pacote version manifest for webpack-bundle-analyzer@3.6.0 fetched in 5ms
4224 silly resolveWithNewModule webpack-bundle-analyzer@3.6.0 checking installable status
4225 http fetch GET 304 https://registry.npmjs.org/typescript 226ms (from cache)
4226 silly fetchPackageMetaData error for typescript@^3.6.4 Unexpected end of JSON input while parsing near '....32","@types/jake":"l'
4227 timing stage:rollbackFailedOptional Completed in 0ms
4228 timing stage:runTopLevelLifecycles Completed in 60876ms
4229 silly saveTree wtm-react@0.0.1
4229 silly saveTree +-- @ant-design/pro-layout@4.6.2
4229 silly saveTree | +-- antd@3.26.11
4229 silly saveTree | | +-- @ant-design/create-react-context@0.2.5
4229 silly saveTree | | | +-- gud@1.0.0
4229 silly saveTree | | | `-- warning@4.0.3
4229 silly saveTree | | |   `-- loose-envify@1.4.0
4229 silly saveTree | | |     `-- js-tokens@4.0.0
4229 silly saveTree | | +-- @ant-design/icons-react@2.0.1
4229 silly saveTree | | | +-- @ant-design/colors@3.2.2
......
```

然后我根据地址访问网页 <https://registry.npmjs.org/typescript>，发现确实存在这样的json内容：
![image](https://user-images.githubusercontent.com/7323999/74739420-be9f4300-5293-11ea-8a6b-cd458c11b1c4.png)

请教如何解决？

**Comment by hd2y** [comment]
今天我也在测试，碰到过同样的问题，我建议使用淘宝镜像 `cnpm` 构建前端项目，然后再运行。
另外需要注意，构建项目之前建议先用 VS 打开项目，否则可能出现构建完成后，项目打开时 VS 未响应。（我是 VS2019）

**Comment by LengYXin** [comment]
修改  npm  镜像地址 为淘宝镜像。
npm config set registry http://registry.npm.taobao.org/
安装 windows node编译工具 
https://www.npmjs.com/package/windows-build-tools

**Comment by LengYXin** [comment]
@hd2y @fawdlstty 
临时解决方案：

1. 去除package.json 中的 node-sass 依赖
2. 将components/other/LayoutSpin/style.sass 修改为 less 文件
3. 将components/other/LayoutSpin/index.tsx 中的 import './style.sass'; 也更正过来。

**Comment by fawdlstty** [comment]
我使用修改npm及安装windows node编译工具的方式解决了编译问题，但发现日志里依旧有异常，
模块：Task
动作：ThrowIfExceptional
ITCode：空
Url：/favicon.ico
备注：System.AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: 'react-app-rewired' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wtm-react@0.0.1 start: `react-app-rewired start` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wtm-react@0.0.1 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm WARN Local package.json exists, but node_modules missing, did you mean to install? )) ---> System.AggregateException: One or more errors occurred. (The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: 'react-app-rewired' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wtm-react@0.0.1 start: `react-app-rewired star

**Comment by hd2y** [comment]
好像我编译过程中看到过类似的错误，但是后来具体操作了什么忘记了。

可能是依赖项需要安装 Python 2，所以安装了 Python 2 然后重新编译项目，你可以试一下。

**Comment by LengYXin** [comment]
> 我使用修改npm及安装windows node编译工具的方式解决了编译问题，但发现日志里依旧有异常，
> 模块：Task
> 动作：ThrowIfExceptional
> ITCode：空
> Url：/favicon.ico
> 备注：System.AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: 'react-app-rewired' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wtm-react@0.0.1 start: `react-app-rewired start` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wtm-react@0.0.1 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm WARN Local package.json exists, but node_modules missing, did you mean to install? )) ---> System.AggregateException: One or more errors occurred. (The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: 'react-app-rewired' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wtm-react@0.0.1 start: `react-app-rewired star

这个错误一般是依赖没有正常安装完成导致的。使用 yarn 重新安装一下 试试。一般 npm 和 node 使用 v12 版本以上的

**Comment by fawdlstty** [comment]
问题已解决。步骤：
修改 npm 镜像地址 为淘宝镜像。
npm config set registry http://registry.npm.taobao.org/
安装 windows node编译工具
https://www.npmjs.com/package/windows-build-tools
安装yarn
https://yarn.bootcss.com/docs/install/#windows-stable
执行命令
```cmd
npm install react-app-rewired --save-dev
yarn add react-app-rewired --dev
npm install customize-cra --save-dev
yarn add customize-cra --dev
```
