### ISSUE TITLE
希望可以提供一个将附件上传到云上的方案

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/WTM#295]
建议框架提供一个附件管理的模块，并且希望可以将附件上传进行调整。

希望在现有 Database, Local, DFS 的基础上，增加一个 Other 选项允许开发者将附件上传部分重写，实现自己的上传逻辑。

比如我希望将附件上传到公有云上进行存储。

例如：
+ 阿里云对象存储 OSS：[https://www.aliyun.com/product/oss](https://www.aliyun.com/product/oss)
+ 腾讯云对象存储 COS：[https://cloud.tencent.com/product/cos](https://cloud.tencent.com/product/cos)
+ 七牛云对象存储 KODO：[https://www.qiniu.com/products/kodo](https://www.qiniu.com/products/kodo)

当开发者根据公有云对象存储开发文档，实现上传功能后，附件上传成功将返回一个附件的链接，存储到附件表中，用户访问该类资源时，可以直接访问该链接。

**Comment by liuliang-wt** [comment]
@alienwow 
感谢你的建议，你说的这个已经在我们的开发计划中。 参见 #255

**Comment by hd2y** [comment]
> @alienwow
> 感谢你的建议，你说的这个已经在我们的开发计划中。 参见 #255

好的，感谢回复，默默期待一下！😃
