### ISSUE TITLE
多附件上传multiupload和多选控件selector在同一页,第二次操作就报错

### ISSUE THREAD

**Issue by fayxue** [dotnetcore/WTM#302]
![image](https://user-images.githubusercontent.com/34908235/75089755-2eb11000-5597-11ea-9a75-e51b8dfce6a7.png)
![image](https://user-images.githubusercontent.com/34908235/75089780-6324cc00-5597-11ea-9b79-0b9fe7bddb4d.png)
在某数据修改页,有这两个控件,图片上传multiupload有值,数据选择selector随便选,然后提交没有问题, 然后再打开这条数据继续修改selector的值 (随便增加或者减少),再提交时就报错了.
按说第二次修改并没有修改图片,而是修改的selector,但是在前端提交数据的时候图片数组却多了一项如图.  因为多的这项并不是guid而是javascript代码,所以后端自动格式化成了全是"0000-000...."的guid,导致最终的报错提示是"INSERT 语句与 FOREIGN KEY 约束"FK_CurrencyImage_FileAttachments_FileId"冲突。该冲突发生于数据库"XXXDB"，表"dbo.FileAttachments", column 'ID'。"

**Comment by liuliang-wt** [comment]
已修复
