### ISSUE TITLE
如何在Grid中创建Post请求的Button？

### ISSUE THREAD

**Issue by faust8883** [dotnetcore/WTM#310]
我阅读了文档，发现在框架提供的方法里，只能在Grid中创建Get请求的Button，请问框架是否提供在Grid中创建Post请求Button的方法？
谢谢！

补充：
例如，在Grid里有一个计数器，每次点击行内的新增按钮，Grid列中的数字加1。这里用Get请求有点不太合适。如果我用OnClientScript，这里我没有使用checkbox选择行，js函数中的ids和datas也就没有数据。
类似这种功能，有没有比较好的实现方式呢？

**Comment by liuliang-wt** [comment]
框架在GridActionParameterTypes是MultiIds或者MultiIdWithNull的时候，点击按钮触发的是Post请求，比如批量修改，批量删除这些都是Post请求。
你要实现的功能应该跟他是get还是post没有关系
