### ISSUE TITLE
LoginUserInfo类Attributes丢失问题

### ISSUE THREAD

**Issue by chhsplend** [dotnetcore/WTM#319]
登陆的时候我会往LoginUserInfo类的Attributes写入值，登陆可以读取到值 。但第二次打开因为缓存没有失效，不需要登陆，但这时Attributes就变NULL了！

**Comment by liuliang-wt** [comment]
LoginUserInfo最终会写到Session里，直接修改他的attribute并不会触发写入session的操作。
你可以用比如 
var temp = LoginUserInfo;
temp.Attribute .... //设置各种变量;
LoginUerInfo = temp;
这样来处理，也就是说必须给LoginUesrInfo这个变量赋值的时候才会写到session里

**Comment by chhsplend** [comment]
`var user = vm.DoLogin();  //登陆的时候，在这里给attrbute赋值，返回LoginUserInfo对象
if (user == null)
{
                return View(vm);
}
else
{
      LoginUserInfo = user;  //再赋值给LoginUserInfo 
....
}`
这样应该是可以的吧，而且事实上，只要不退出也是能行的。但是退出后再登陆，如果SESSION没失效，就不需要登陆，attrbute就为NULL

**Comment by liuliang-wt** [comment]
哦，我知道了，这应该是个bug
@alienwow 保持登录状态的时候，LoginUser里的Attributes没有被保存

**Comment by liuliang-wt** [comment]
最新版本可以通过继承BaseController或BaseApiController之后 重写 GetLoginUserInfo 方法，当session没有失效但是用户信息找不到的时候框架会执行这个 GetLoginUserInfo方法，这个方法默认只是去数据库里读取用户数据，没有给附加的Attribute赋值。你重写这个方法给Attribute赋值就可以了
