### ISSUE TITLE
[Bug]前后端分离React版本，学校类型在列表中能展示，在详情页中显示不出来，接口返回的类型是0或1

### ISSUE THREAD

**Issue by wangj90** [dotnetcore/WTM#32]
- 列表页
![image](https://user-images.githubusercontent.com/25636510/62708327-c305bc00-ba25-11e9-8369-6e0e0cddbc97.png)
- 详情页
![image](https://user-images.githubusercontent.com/25636510/62708353-cef17e00-ba25-11e9-8f6b-0c47ed4ddd40.png)

**Comment by liuliang-wt** [comment]
非常感谢，我们已经发现了这个bug，会在下个版本中修复
