### ISSUE TITLE
联动子ComboBox是否可以获取祖父级ComboBox的value

### ISSUE THREAD

**Issue by XIO-OIX** [dotnetcore/WTM#321]
![image](https://user-images.githubusercontent.com/31812077/75736071-36ab4580-5d37-11ea-99ce-3a38d9f8f4f0.png)

如上图正常逻辑：选学校、选专业、选学生
在选择专业后，服务端查询学生时需要知道是哪个学校
该如何在查询学生的逻辑中获取学校信息

**Comment by liuliang-wt** [comment]
你在查询学生的时候，框架给你传了专业的id，你也是通过这个专业id查的学生，那你有了这个专业id一样可以找到所属学校啊

**Comment by XIO-OIX** [comment]
专业可能是公共的，每个学校都有这个专业，做不到一对一

**Comment by liuliang-wt** [comment]
那你的数据结构是怎么设计的， 专业是公共的，跟学校没有关联关系？ 然后学生只跟专业有关联关系？那样你肯定是不知道学生是哪个学校的

**Comment by XIO-OIX** [comment]
谢谢，我明白您的意思了。
