### ISSUE TITLE
文件上传, FileAttachment属性为null

### ISSUE THREAD

**Issue by XIO-OIX** [dotnetcore/WTM#323]
![image](https://user-images.githubusercontent.com/31812077/75770022-1eace380-5d82-11ea-9e3c-a3e1dea2bf9c.png)
选择文件提交
![image](https://user-images.githubusercontent.com/31812077/75770086-41d79300-5d82-11ea-83ca-151bedb4cc15.png)
FileAttachment属性为Null,无法获取文件value

**Comment by liuliang-wt** [comment]
已修复，下一版会更新

**Comment by XIO-OIX** [comment]
![image](https://user-images.githubusercontent.com/31812077/75836164-eba73600-5dfb-11ea-9e5f-e8bb5cf841ea.png)
FileAttachment类型

**Comment by XIO-OIX** [comment]
我必须绑定另外一个string列作为value数据返回字段是吗
