### ISSUE TITLE
Mysql没有版本信息导致驱动程序生成SQL代码错误

### ISSUE THREAD

**Issue by byebyebt** [dotnetcore/WTM#335]
在mysql5.7环境中，efcore 的RenameColumn操作生成的sql语句是“rename XXX to YYY”，这个只能在mysql8以上才能用。生成错误的原因是usemysql时没有传入版本信息，导致sql语句与数据库版本不匹配（官方回复说没有版本信息就默认为最新版本），建议把EmptyContext的下面代码：

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            switch (DBType)
            {
                case DBTypeEnum.SqlServer:
                    optionsBuilder.UseSqlServer(CSName);
                    break;
                case DBTypeEnum.MySql:
                    optionsBuilder.UseMySql(CSName);
                    break;
             。。。。。。
```

改成

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            switch (DBType)
            {
                case DBTypeEnum.SqlServer:
                    optionsBuilder.UseSqlServer(CSName);
                    break;
                case DBTypeEnum.MySql:
                    optionsBuilder.UseMySql(CSName, mySqlOptions => mySqlOptions
                     .ServerVersion(new Pomelo.EntityFrameworkCore.MySql.Storage.ServerVersion(new Version(5, 7, 22), ServerType.MySql)));
                    break;
          。。。。。。
```

（版本数据在配置文件设置）

**Comment by Refactoring** [comment]
啥错误，抛上来，我也看看。  我也用的MySQL，暂时还没提示错误。

**Comment by liuliang-wt** [comment]
5.7运行的时候没有问题，你是说migration的时候么

**Comment by byebyebt** [comment]
@liuliang-wt  问题的由来是这样的：

我修改了一个字段名称，migration自动生成了一个DropColumn和个AddColumn， 这样这个字段原有的数据就会被删掉，所以我把这两个操作删掉改成了RenameColumn，但是RenameColumn操作生成的Sql语句是“alter table XXX rename column YYY to ZZZ”，这个是mysql8.0才支持的语法，在5.7上是不能执行的。

我在驱动程序的github上问了一下，他们回复说之所以会生成错误的Sql语句，是因为在UseMysql的时候可能没有指定mysql版本号，所以按照最新版处理，那么在版本间不兼容的功能上肯定就会出问题（比如重命名字段在8.0就改了）。

WTM现在执行起来没问题应该是还没有使用到这种存在版本差异的功能，一旦使用到恐怕就会出问题，所以建议让用户在配置文件里配置版本号，在UseMysql的时候把版本号加上，这样肯定就没问题了。
