### ISSUE TITLE
[vue]自定义主键为string时无法提交

### ISSUE THREAD

**Issue by KnifezZZ** [dotnetcore/WTM#345]
当主键自定义为string时前端填写后但无法提交，跟踪代码原因为formdata中的ID被移除。
具体：`vue-custom/mixin/form-mixin.ts`中onAdd方法移除了ID
**解决方案**
修改如下，判断id是否为空，不为空就是自定义主键，需要传递值，否则移除。
````
      if(formData.Entity["ID"]===""){
        delete formData.Entity["ID"];
      }
````

**Comment by liuliang-wt** [comment]
已修改
