### ISSUE TITLE
搜索BUG

### ISSUE THREAD

**Issue by ysq5202121** [dotnetcore/WTM#350]
在使用搜索的时候，如果不在第一页进行带条件搜索，将会查询不到任何数据，原因是有分页信息，直接查询某一页的数据，而不会根据条件返回第一页的数据

**Comment by liuliang-wt** [comment]
额，你说的啥意思，不是很理解

**Comment by ysq5202121** [comment]
例如：不带任何条件点击搜索，在第3页找到一个商品，然后点击第2页，在第2页输入第3页的商品点击搜索，这个时候是搜索不到该数据的，原因是搜索的时候自动带入了分页信息，会直接查询第2页+条件进行搜索。

**Comment by liuliang-wt** [comment]
哦，确实是，这是上一版为了解决api的其他问题导致的，很快会修复
