### ISSUE TITLE
生成的第一个项目，编译时提示：MSB3086	

### ISSUE THREAD

**Issue by tanshiyang** [dotnetcore/WTM#351]
MSB3086	任务未能使用 SdkToolsPath“”或注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86”找到“al.exe”。请确保已设置 SdkToolsPath，在 SdkToolsPath 之下的相应处理器特定位置存在该工具，并且已安装 Microsoft Windows SDK	wtm_test	d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3639

**Comment by liuliang-wt** [comment]
老版本的vs有这个问题，你可以运行 visual studio installer，手动安装一下 netfxsdk 4.7.2

**Comment by tanshiyang** [comment]
安装这个解决了：.NET Framework 4.7.2 Developer Pack
