### ISSUE TITLE
[vue]列表按钮创建功能未实现，设置新的tab页弹出页面未实现

### ISSUE THREAD

**Issue by KnifezZZ** [dotnetcore/WTM#355]
在vm中添加 `this.MakeAction("WebSite","","同步",“同步",paraType:GridActionParameterTypesEnum.MultiIds),`后无效，同样代码layui版本可以正常显示。
同样设置SetIsRedirect、SetShowDialog也无效。

**Comment by liuliang-wt** [comment]
这不是bug，react和vue这些前后端分离的都需要在前端写这些按钮。 框架提供的跟页面相关的方法只有不分离的时候才会起作用
