### ISSUE TITLE
VUE版未分配导入权限，依然显示导入按钮

### ISSUE THREAD

**Issue by 406841895** [dotnetcore/WTM#358]
![c](https://user-images.githubusercontent.com/38776389/80331195-fb7e4c00-8879-11ea-8239-63218492e45a.png)

查询可用，有导入按钮，并且导入功能可用。

![d](https://user-images.githubusercontent.com/38776389/80331205-020cc380-887a-11ea-8481-1ad994651bed.png)

权限里未分配导入功能

**Comment by haozl1129** [comment]
已修复，默认传入的参数错误；也可以自动以传入 actionKeys 参数定义权限
![image](https://user-images.githubusercontent.com/19700448/80390585-31a1e700-88df-11ea-81b7-6cff1fa66c0f.png)
