### ISSUE TITLE
自定义主键出错

### ISSUE THREAD

**Issue by zooyoo** [dotnetcore/WTM#389]
![image](https://user-images.githubusercontent.com/12769712/84583021-55d16d00-ae26-11ea-872a-95ddb8549085.png)

![image](https://user-images.githubusercontent.com/12769712/84583031-73063b80-ae26-11ea-9b2d-41f57bb047a0.png)

**Comment by liuliang-wt** [comment]
new int ID， 注意大小写，否则其实没有覆盖基类的同名变量
