### ISSUE TITLE
导入的数据顺序跟excel不一样

### ISSUE THREAD

**Issue by zxp6499** [dotnetcore/WTM#39]
作者好，导入excel表格后，列表显示的顺序跟excel表格里的顺序不一样，希望还是能一致

**Comment by liuliang-wt** [comment]
列表中是可以配置根据任何一列排序的，在相应ListVM中可以设置，跟导入数据的顺序没有关系

**Comment by zxp6499** [comment]
谢谢，那可以自动排序吗，不需要点击列头，显示就是排序好的，我试过SetSort()，必须点一下才行。
