### ISSUE TITLE
vue版列表搜索栏多了两个字，怎么去掉。。

### ISSUE THREAD

**Issue by zooyoo** [dotnetcore/WTM#390]
vue版列表搜索栏多了两个字“信息””，这是干啥用的，还单独占了一行，不晓得怎么来的。。怎么去掉

![image](https://user-images.githubusercontent.com/12769712/84594461-f5bde380-ae84-11ea-9acf-b87c7effcee2.png)

**Comment by liuliang-wt** [comment]
在 ClientApp\src\pages\模块名\Index.vue里定义了搜索条件的控件，你检查一下是不是多写了什么
