### ISSUE TITLE
vue版搜索栏给下拉框或单选按钮组赋初值没有效果

### ISSUE THREAD

**Issue by zooyoo** [dotnetcore/WTM#393]
![image](https://user-images.githubusercontent.com/12769712/85203367-dd940b80-b33f-11ea-8583-816e81a55583.png)

![image](https://user-images.githubusercontent.com/12769712/85203376-fd2b3400-b33f-11ea-98d7-9f2c92adf933.png)

想让下拉框和单选按钮默认选中第一项，给v-model赋值0没生效

![image](https://user-images.githubusercontent.com/12769712/85203401-2e0b6900-b340-11ea-983f-6c65219e7a57.png)

是我的使用姿势不对吗。。？

**Comment by haozl1129** [comment]
defaultValue 是设置 默认值的；

**Comment by haozl1129** [comment]
![image](https://user-images.githubusercontent.com/19700448/85228677-62058d80-b417-11ea-90f6-55edf68c7b26.png)
例如
