### ISSUE TITLE
多语言版本导入会报错

### ISSUE THREAD

**Issue by ysq5202121** [dotnetcore/WTM#396]
使用Localizer这个索引器，导入的时候没有初始化（null），取值的时候报错。

**Comment by liuliang-wt** [comment]
能描述的再详细一点么，在哪一步报错，报什么错

**Comment by ysq5202121** [comment]
public override bool BatchSaveData()
        {

            return base.BatchSaveData();
        }
BatchSaveData这个方法里面会初始化BaseCRUDVM对象,但是没有初始化Localizer，导致在
  public override void Validate()
        {
            var stockLocation = DC.Set<StockLocation>().SingleOrDefault(a => a.StockLocationCode == Entity.StockLocationCode);
            if (stockLocation == null) 
            {
                MSD.AddModelError("error", Entity.StockLocationCode+ Localizer["StockLocationDetailVM.1582"]);
                return;
            }
            if (stockLocation.Status == EnumStockLocationStatus.Disable)
            {
                MSD.AddModelError("error", Entity.StockLocationCode + Localizer["StockLocationDetailVM.1788"]);
                return;
            }
            if (!DC.Set<Products>().Any(a => a.Sku == Entity.Sku))
            {
                MSD.AddModelError("error", Entity.Sku + Localizer["StockLocationDetailVM.1977"]);
                return;
            }
            
            base.Validate();
        }
这里进行验证会抛出null异常.

**Comment by liuliang-wt** [comment]
没能复现这个问题，你确定是Localizer为空么

**Comment by ysq5202121** [comment]
是的,因为我调试过，而且你可以看源代码,Localizer这个索引器是根据对象来的，如果初始化不是CreateVM创建的是没有值的,导入里面好像是用反射取的.

**Comment by ysq5202121** [comment]
要注意你不能在导入对象里面实现哦，在BaseCRUDVM里面实现,看上面的源代码

**Comment by ysq5202121** [comment]
public class *********mportVM : BaseImportVM<*********TemplateVM,*********>
 {
   public override bool BatchSaveData()
  {

        return base.BatchSaveData();
    }
}

  public partial class *****VM : BaseCRUDVM<****>
{
public override void Validate()
{
var stockLocation = DC.Set().SingleOrDefault(a => a.StockLocationCode == Entity.StockLocationCode);
if (stockLocation == null)
{
MSD.AddModelError("error", Entity.StockLocationCode+ Localizer["StockLocationDetailVM.1582"]);
return;
}
if (stockLocation.Status == EnumStockLocationStatus.Disable)
{
MSD.AddModelError("error", Entity.StockLocationCode + Localizer["StockLocationDetailVM.1788"]);
return;
}
if (!DC.Set().Any(a => a.Sku == Entity.Sku))
{
MSD.AddModelError("error", Entity.Sku + Localizer["StockLocationDetailVM.1977"]);
return;
}

        base.Validate();
    }

}

base.BatchSaveData()会自动调用BaseCRUDVM继承类的方法

**Comment by liuliang-wt** [comment]
源码中在BaseImportVM里有：
 IBaseCRUDVM<P> vm = null;
            DuplicatedInfo<P> dinfo = null;
            if (vmtype != null)
            {
                vm = vmtype.GetConstructor(System.Type.EmptyTypes).Invoke(null) as IBaseCRUDVM<P>;
                vm.CopyContext(this);
                dinfo = (vm as dynamic).SetDuplicatedCheck();
            }
这里的 vm.CopyContext(this); 会给Localizer赋值。
我根据你上面的代码测试，仍然无法复现。
你可以给我发一个最简单的可以复现这个问题的代码么？

**Comment by liuliang-wt** [comment]
或者你直接运行，把报错的完整内容发给我看看

**Comment by ysq5202121** [comment]
看了下我的是没有
   public void CopyContext(BaseVM vm)
    {
      this.DC = vm.DC;
      this.FC = vm.FC;
      this.CurrentCS = vm.CurrentCS;
      this.CreatorAssembly = vm.CreatorAssembly;
      this.MSD = vm.MSD;
      this.Session = vm.Session;
      this.ConfigInfo = vm.ConfigInfo;
      this.DataContextCI = vm.DataContextCI;
      this.UIService = vm.UIService;
      this.LoginUserInfo = vm.LoginUserInfo;
    }
5月3日修复了.......................................
感谢！，看样子需要升级了！

**Comment by ysq5202121** [comment]
可关闭

**Comment by liuliang-wt** [comment]
。。。
