### ISSUE TITLE
Vue版本正则匹配问题

### ISSUE THREAD

**Issue by zxj2433** [dotnetcore/WTM#397]
使用正则时 ，ModelState.IsValid总是不通过
![TIM图片20200626210111](https://user-images.githubusercontent.com/52045796/85859818-5be52780-b7f0-11ea-8ae8-a78c3f7c2230.jpg)
![TIM图片20200626210117](https://user-images.githubusercontent.com/52045796/85859835-61427200-b7f0-11ea-9f5b-109753d48b89.png)
但是注释掉Model里的正则，在ViewModel里就可以正确匹配上
![TIM图片20200626210124](https://user-images.githubusercontent.com/52045796/85859872-6b647080-b7f0-11ea-961a-40c468cd58f5.png)

**Comment by liuliang-wt** [comment]
[RegularExpression]是.netcore自带的，框架没有做其他处理，你试试不加开始的那个@

**Comment by zxj2433** [comment]
> [RegularExpression]是.netcore自带的，框架没有做其他处理，你试试不加开始的那个@

就是之前没加@不行我才加上的......奇怪，我换成layui的也不行，如果语法错了在ViewModel里应该不通过的吧？
