### ISSUE TITLE
多附件上传时必填验证不通过

### ISSUE THREAD

**Issue by MrQY** [dotnetcore/WTM#401]
![20200701140425](https://user-images.githubusercontent.com/4926925/86208926-120b9100-bba4-11ea-803d-2c0fadbb9616.jpg)

**Comment by TomLiu-GitHub** [comment]
我也有这个问题,你的富文本框的图片是如何上传的?

**Comment by liuliang-wt** [comment]
最新的源码已经修改了这个问题
