### ISSUE TITLE
官网创建工程出现问题

### ISSUE THREAD

**Issue by DavidDXY** [dotnetcore/WTM#403]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1202	包 Microsoft.Win32.Primitives 4.3.0 与 netcoreapp3.1 (.NETCoreApp,Version=v3.1) 不兼容。 包 Microsoft.Win32.Primitives 4.3.0 支持:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	CommServer.Test	D:\VCSharpProj\CommServer\CommServer.Test\CommServer.Test.csproj	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1202	包 System.Net.NameResolution 4.3.0 与 netcoreapp3.1 (.NETCoreApp,Version=v3.1) 不兼容。 包 System.Net.NameResolution 4.3.0 支持:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	CommServer.Test	D:\VCSharpProj\CommServer\CommServer.Test\CommServer.Test.csproj	1

无法编译

**Comment by liuliang-wt** [comment]
Microsoft.Win32.Primitives 4.3.0 这个是你自己加的吧，这个不支持.netcore 3.1啊

**Comment by DavidDXY** [comment]
> Microsoft.Win32.Primitives 4.3.0 这个是你自己加的吧，这个不支持.netcore 3.1啊

我没有修改工程，下载用vs打开后编译直接报错了
![image](https://user-images.githubusercontent.com/28525559/86751444-3dddb980-c071-11ea-9bd2-adb60e06ff2d.png)

**Comment by liuliang-wt** [comment]
额。。。我这边复现不了你的问题。你确定你使用的是visual studio 2019，并且安装了 .netcore 3.1的sdk么
