### ISSUE TITLE
请问有增加Blazor的计划么？

### ISSUE THREAD

**Issue by ElderJames** [dotnetcore/WTM#405]
Blazor对于.NET开发者更友好、效率更高！

欢迎来使用 Ant Design Blazor！

组件库：https://github.com/ant-design-blazor/ant-design-blazor
Admin：https://github.com/ant-design-blazor/ant-design-pro-blazor

**Comment by liuliang-wt** [comment]
有，下一个大版本会加入blazor的支持

**Comment by ElderJames** [comment]
非常棒！希望能用上ant design blazor~

**Comment by liuliang-wt** [comment]
@ElderJames 我最关心的其实是表格，大部分复杂需求都需要表格的前台展示，比如动态添加，修改，删除某行的单元格，分组，树形表格，服务器端排序。这些我看你那个现在还没有哇

**Comment by ElderJames** [comment]
分组和属性还没支持，增加修改删除会做在Pro里面，因为是多个组件的组合功能，服务端查询是支持的，在OnChange事件里，会把排序字段传出来。

**Comment by liuliang-wt** [comment]
Pro版本也是开源的么，啥协议啊。

**Comment by ElderJames** [comment]
开源，Apache 2.0

**Comment by liuliang-wt** [comment]
好，那我研究一下，加油，共同进步

**Comment by ElderJames** [comment]
👏👏感谢支持

**Comment by iticrush** [comment]
wow 非常期待！强强合作啊！

**Comment by ElderJames** [comment]
请问开始做了吗？
