### ISSUE TITLE
Layui版本，同一页多个Combobox冲突问题

### ISSUE THREAD

**Issue by cfqdream** [dotnetcore/WTM#409]
同一个页面放有Combobox A,允许多选，没有设置 LinkField,TriggerUrl，然后放Combobox B, Combobox C, B有设置 LinkField,TriggerUrl跟 Combobox C联动，没有在 Combobox B 上进行选择前，可以在 Combobox A 进行多选，但是在 Combobox B进行选择后，就不能在 Combobox A  上进行多选了，只能单选。

**Comment by liuliang-wt** [comment]
嗯，多选的combobox不能正确的支持联动，这是个历史遗留问题

**Comment by liuliang-wt** [comment]
新版本已修复
