### ISSUE TITLE
设置菜单不显示不起作用

### ISSUE THREAD

**Issue by mwb20** [dotnetcore/WTM#414]
我想把某些菜单对用户隐藏起来，但是设置后不起作用，最后我通过修改WalkingTec.Mvvm.Mvc.Admin项目下的AccountController控制器内的CheckLogin方法达到了效果，主要修改的代码在`198`行
将原来的
`var topdata = data.Where(x => x.ParentId == null).ToList().FlatTree(x => x.DisplayOrder).Where(x => x.IsInside == false || x.FolderOnly == true || string.IsNullOrEmpty(x.MethodName)).ToList();`
改成
`var topdata = data.Where(x => x.ParentId == null && x.ShowOnMenu).ToList().FlatTree(x => x.DisplayOrder).Where(x => (x.IsInside == false || x.FolderOnly == true || string.IsNullOrEmpty(x.MethodName)) && x.ShowOnMenu).ToList();`

我不知道我改的方式对不对，希望能修复一下，谢谢！

**Comment by liuliang-wt** [comment]
不需要改，如果是在非调试模式下，框架会读取你菜单管理里配置的菜单。你说设置后不起作用是啥意思

**Comment by mwb20** [comment]
> 不需要改，如果是在非调试模式下，框架会读取你的菜单管理里配置的菜单。你说设置后不起作用是啥意思

比如像客户和客户充值记录这样的功能，我现在在客户列表的操作列中增加一个查看充值记录的按钮，点击后在弹出的页面只会显示这个客户的充值记录，但是充值记录里的功能又需要权限判断，我的做法是增加一个充值记录的菜单在这个菜单上做权限处理，然后再把这个菜单给隐藏起来，但是我在菜单管理下面设置这个菜单不显示时却没起作用，关闭调试模式还是一样的没效果`"IsQuickDebug": false`，最后我修改了底层源码后实现了我想要的效果。你可以设置某个菜单不显示应该能重现问题
![TIM截图20200810161023](https://user-images.githubusercontent.com/7752000/89763163-8c74ec80-db24-11ea-8786-5f8a5aec399b.png)

**Comment by liuliang-wt** [comment]
哦，还真是，是个bug。。。下一版本修复一下
