### ISSUE TITLE
生成的index.cshtml里面的wt:grid不能指定ID

### ISSUE THREAD

**Issue by qzdata** [dotnetcore/WTM#416]

**Comment by qzdata** [comment]
生成的index.cshtml里面的wt:grid指定ID，搜索按钮点击报错

**Comment by liuliang-wt** [comment]
<wt:grid>指定id的时候，<SearchPanel>里也要指定相应的gridid

**Comment by qzdata** [comment]
如果自定义了GRID的ID，searchpanel里需要指定grid-id
