### ISSUE TITLE
BasePagedListVM的DoSearch中的一处逻辑是否有问题

### ISSUE THREAD

**Issue by nodiy1982** [dotnetcore/WTM#420]
![image](https://user-images.githubusercontent.com/28780494/91257468-8c1f5700-e79c-11ea-8af8-a61619b6c934.png)
这里是根据TModel的类型来判断是否应该添加x=>x.IsValid = true的查询条件，当TModel是PersistPoco而被查询的Set<T>并不是一个PersistPoco时会引发Property 'Boolean IsValid' is not defined的异常。

**Comment by liuliang-wt** [comment]
感谢指正，确实有问题
