### ISSUE TITLE
ConnectionStrings多个连接串，有一个掉线，整站点不能用

### ISSUE THREAD

**Issue by qzdata** [dotnetcore/WTM#424]
ConnectionStrings中有多个数据库连接串，如果其中某一个掉线，整个站点挂掉，可否改成只判断default或者连接串加个属性是否参与启动判断

**Comment by liuliang-wt** [comment]
感谢指正，已修复

**Comment by qzdata** [comment]
> 感谢指正，已修复

能否告知是哪个文件的更新，我这边因为数据库版本问题，我用的是.NET CORE2.2的版本，没办法整个项目升到最新版，谢谢

**Comment by liuliang-wt** [comment]
2.2版本的也有对应的更新，应该是2.7.3.1，你更新到这个版本就行了。


-------- 原始邮件 --------
发件人： qzdata <notifications@github.com>
日期： 2020年9月14日周一 傍晚5:24
收件人： dotnetcore/WTM <WTM@noreply.github.com>
抄送： liuliang-wt <liuliang79@live.com>, Comment <comment@noreply.github.com>
主 题： Re: [dotnetcore/WTM] ConnectionStrings多个连接串，有一个掉线，整站点不能用 (#424)

感谢指正，已修复

能否告知是哪个文件的更新，我这边因为数据库版本问题，我用的是.NET CORE2.2的版本，没办法整个项目升到最新版，谢谢

―
