### ISSUE TITLE
ISubFile在API接口中生成的json字符串有问题

### ISSUE THREAD

**Issue by bigccc** [dotnetcore/WTM#425]
`{"Data":[{"HotelName":"测试酒店","Address":"麒麟区","Telephone":"1390874****","MainPicId":"683d45f5-3ef9-464d-9094-7f64071b4707","Photos":[{"HotelId":"7f9ce13a-5a7b-48d6-bc98-03ce7de31675","Hotel":null,"FileId":"685fb6f9-276a-4abf-9d84-cbae26a9ba1b","File":null,"order":0,"ID":"1c3a1c1f-fbea-4bab-9abe-4e34e5a17172"},{"HotelId":"7f9ce13a-5a7b-48d6-bc98-03ce7de31675","Hotel":null,"FileId":"4f6e1117-4d08-43c8-96af-c6a4f29bd64d","File":null,"order":0,"ID":"efd134a4-db12-4b74-97d9-a2fcc35daecd"}],"IsRecommand":true,"Star":三星,"Type":会议酒店,"Longitude":123.123123,"Latitude":321.321321,"Introduce":<p>A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打</p>,"CheckInNotes":<p>A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打A手动阀A手动阀打</p>,"TempIsSelected":"0","ID":"7f9ce13a-5a7b-48d6-bc98-03ce7de31675","LAY_CHECKED":false}],"Count":1,"Page":1,"PageCount":1,"Msg":"success","Code":200}`

**Comment by liuliang-wt** [comment]
框架默认的列表并不能自动在某一列上显示多个图片，你可以输出一个photoid的逗号分隔的字符串，然后前台去解析

**Comment by liuliang-wt** [comment]
已修复
