### ISSUE TITLE
请教如何实现订单主子档一起编辑

### ISSUE THREAD

**Issue by kevin100702** [dotnetcore/WTM#433]
请教如何实现如下图类似的主子档一起编辑的功能，是否有范例可供参考，或者有其他形式的实现也可以？
![主子档编辑](https://user-images.githubusercontent.com/12688812/94220399-6ad89480-ff1b-11ea-84eb-001702078ae9.png)

**Comment by liuliang-wt** [comment]
csdn上的视频教程有介绍，源码中的demo，学校管理里也有一个主子表同时添加的示例

**Comment by kevin100702** [comment]
谢谢，亮哥，正在CSDN学习中
