### ISSUE TITLE
如果使用GUID作为主键，建议使用有序GUID

### ISSUE THREAD

**Issue by kinglionsoft** [dotnetcore/WTM#437]
https://github.com/dotnetcore/WTM/blob/a4d030a80dc8bc89a3e41767b7d31eb1bad41224/src/WalkingTec.Mvvm.Core/Models/TopBasePoco.cs#L26

[https://mariadb.com/kb/en/guiduuid-performance/](https://mariadb.com/kb/en/guiduuid-performance/)

**Comment by liuliang-wt** [comment]
目前使用了EF默认的有序guid
