### ISSUE TITLE
框架数据权限能否提供字段权限控制

### ISSUE THREAD

**Issue by Qiulin-Git** [dotnetcore/WTM#439]
现实中我们有一些字段一般人是不能看到的，比如单价和金额，销售人员和财务可以看到，其他人不能看到，这种情况我们就要用字段权限去控制，有权限的人能看到单价和金额 ，没有权限的人不能看到这两个字段或者这两个字段的内容显示成 *

**Comment by liuliang-wt** [comment]
这个属于数据安全的范畴，和传统的数据权限还不太一样，我考虑考虑后续也许会加上这个功能
