### ISSUE TITLE
官网生成React、多项目分离代码，用户修改密码报错

### ISSUE THREAD

**Issue by venorie** [dotnetcore/WTM#452]
# 生成配置
![image](https://user-images.githubusercontent.com/33367805/108816527-4af3ec80-75f1-11eb-8a91-8879609aad0b.png)
# bug重现
- 调试项目
- 访问页面
- 修改密码并提交
![image](https://user-images.githubusercontent.com/33367805/108816838-d53c5080-75f1-11eb-8f00-c8608b2ba27b.png)

# bug分析
## React中提交字段不正确
![image](https://user-images.githubusercontent.com/33367805/108816995-25b3ae00-75f2-11eb-99d0-6e3b742d4141.png)
![image](https://user-images.githubusercontent.com/33367805/108817006-2d735280-75f2-11eb-89d2-5c8b5376a334.png)
Controller中验证ITCode字段，但提交的是UserId
## 提交的url错误
- 正确url: /api/_Account/ChangePassword
![image](https://user-images.githubusercontent.com/33367805/108817524-f9e4f800-75f2-11eb-9566-cedad00b47c8.png)
- 提交url: /api/Account/ChangePassword
![image](https://user-images.githubusercontent.com/33367805/108817465-e76abe80-75f2-11eb-8548-aefa78e33be5.png)
提交url缺少了下划线

**Comment by liuliang-wt** [comment]
感谢指正，官网的项目生成已经修复
