### ISSUE TITLE
V5.0.6中，示例代码学校功能中，导入excel功能学校名称未验证必填BUG

### ISSUE THREAD

**Issue by taoyiqi** [dotnetcore/WTM#453]
V5.0.6中，示例代码学校功能中，导入excel时，若学校名称为空，也能写入数据库，正常应该提示学校名称不能为空。
![学校名称为空为校验](https://user-images.githubusercontent.com/10924828/108971109-12214980-76bd-11eb-8b56-f336f55fe1df.png)

**Comment by liuliang-wt** [comment]
感谢指正，已经修复，会在5.0.7中发布

**Comment by taoyiqi** [comment]
架构设计和实施者才是王者，我们只是一颗螺丝钉，希望能贡献微薄之力。
