### ISSUE TITLE
v5.0.7自动生成项目Bug

### ISSUE THREAD

**Issue by xiangpingtang** [dotnetcore/WTM#454]
一.用户管理-图片
![image](https://user-images.githubusercontent.com/31881104/109993311-1e557880-7d47-11eb-849a-d5bdb99a9970.png)
按照教程自动生成项目。在用户管理页面上传用户照片，再进行退出登录操作。

![image](https://user-images.githubusercontent.com/31881104/109994944-c61f7600-7d48-11eb-9949-838d79d71d1d.png)
用户照片有很大概率显示不出来。
![image](https://user-images.githubusercontent.com/31881104/109995089-ebac7f80-7d48-11eb-8df2-3df8ad8ee5cb.png)
预览同理

二.用户管理-批量删除
![image](https://user-images.githubusercontent.com/31881104/109995319-27dfe000-7d49-11eb-9ace-49481f5229b5.png)
./Areas/_Admin/Views/FrameworkUser/BatchDelete.cshtml  第三行遗漏<Program>

三.用户管理-导出Excel
![F DZ) 122N6X`@4${B5}N89](https://user-images.githubusercontent.com/31881104/109996482-3e3a6b80-7d4a-11eb-907f-9f3d6059266a.png)
导出数据未根据枚举上的描述显示

四.日志
![image](https://user-images.githubusercontent.com/31881104/109997501-38915580-7d4b-11eb-992d-8c2f9723d501.png)
登录成功直接进入日志页面，若日志无数据，有很小概率出现错误信息。（反复测试得出结果）

**Comment by liuliang-wt** [comment]
一、图片问题无法复现，如果是在vs中调试，不要用360之类的浏览器，会和vs的调试冲突。另外可以在浏览器里按F12，看看显示图片的地址返回的什么错误。

二、批量删除是生成项目时候的问题，已经修复，从官网重新生成就好了。
三、框架不支持sqlserver 2008以下，列表错误一般是你用的sqlserver 2008

**Comment by xiangpingtang** [comment]
已解决
