### ISSUE TITLE
TreePoco<T>在WTM 2.x/3.x 的类库里没有找到

### ISSUE THREAD

**Issue by ToMakeSense** [dotnetcore/WTM#455]
`TreePoco<T>`在WTM 2.x/3.x版本(.Net core 3.1)类库里没有找到，官方文档里也没有，在WTM 5.x(.Net 5.0)的文档下是有的，所以WTM 2.x/3.x版本不支持`TreePoco<T>`吗？奇怪的是在 [快速开始/5.0新变化](https://wtmdoc.walkingtec.cn/#/WhatsNew/New) 里似乎没有提到这个功能。

**Comment by liuliang-wt** [comment]
2.3/3.x 是用接口的方式 ITreeData，你可以在树形控件的文档中看到介绍：
http://wtmdoc.walkingtec.cn/#/UI/Tree

**Comment by ToMakeSense** [comment]
@liuliang-wt 指正文档里的一处相关问题
1. 在`模型层 \ 创建模型` section，即https://wtmdoc.walkingtec.cn/#/Model/Poco, 切换到 2.x/3.x 没有提及 ITreeData 接口
2. 在`页面层 \ 树形容器` section，即http://wtmdoc.walkingtec.cn/#/UI/Tree,  5.x 版本表述错误 (应该改成TreePoco基类)
```
继承了ITreeData接口的模型，可以方便的调用框架提供的函数生成TreeContainer需要的数据格式,
```
