### ISSUE TITLE
生成的项目中（LayUI模式），Test项目中的Login中有错误

### ISSUE THREAD

**Issue by 5653325** [dotnetcore/WTM#456]
第33行 FrameworkUser v = new FrameworkUser(); //爆红色，无法编译通过
是否应该是FrameworkUserBase v = new FrameworkUserBase();

**Comment by liuliang-wt** [comment]
并没有发现这个问题，新生成的项目中是有FrameworkUser这个类的

**Comment by 5653325** [comment]
> 并没有发现这个问题，新生成的项目中是有FrameworkUser这个类的

大佬，忘了说了，是core3.1单一项目有这个问题。

**Comment by liuliang-wt** [comment]
还真是，已经修复
