### ISSUE TITLE
实体里面 FileAttachment  类型属性设置[NotMapped]时，弹出编辑框时会报System.NullReferenceException错误；

### ISSUE THREAD

**Issue by cfqdream** [dotnetcore/WTM#458]
比如代码： 
  public class Student : BasePoco
  {
        [Display(Name = "账号")]
        [Required(ErrorMessage = "{0}是必填项")]
        [StringLength(50, ErrorMessage = "{0}最多输入{1}个字符")]
        public string LoginName { get; set; }
       public Guid? PhotoId { get; set; }
        [Display(Name = "照片")]
        [NotMapped]
        public FileAttachment Photo { get; set; }
}

StudentController.cs
        [ActionDescription("Sys.Get")]
        [HttpGet("{id}")]
        public StudentVM Get(string id)
        {
           //这个位置会报错
            var vm = Wtm.CreateVM<StudentVM>(id);             
            return vm;
        }
跟踪代码，应该在 BaseCRUDVM.cs 进行修改
    protected virtual TModel GetById(object Id)
    ...
把   foreach (var f in fa)
            {
                var fname = DC.GetFKName2<TModel>(f.Name);
                var fid = typeof(TModel).GetSingleProperty(fname).GetValue(rv);
                if (fid != null)
                {
                    var fp = Wtm.HttpContext.RequestServices.GetRequiredService<WtmFileProvider>();
                    var file = fp.GetFile(fid?.ToString(), false, DC);
                    rv.SetPropertyValue(f.Name, file);
                }
            }
   里面的 var fid = typeof(TModel).GetSingleProperty(fname).GetValue(rv); 修改为
               var fid = typeof(TModel).GetSingleProperty(fname)?.GetValue(rv);

**Comment by liuliang-wt** [comment]
这个photo是和photoid一起定义外键的，不能设置为notmapped



-------- 原始邮件 --------
发件人： cfqdream ***@***.***>
日期： 2021年3月12日周五 下午2:39
收件人： dotnetcore/WTM ***@***.***>
抄送： Subscribed ***@***.***>
主 题： [dotnetcore/WTM] 实体里面 FileAttachment 类型属性设置[NotMapped]时，弹出编辑框时会报System.NullReferenceException错误； (#458)

比如代码：
public class Student : BasePoco
{
[Display(Name = "账号")]
[Required(ErrorMessage = "{0}是必填项")]
[StringLength(50, ErrorMessage = "{0}最多输入{1}个字符")]
public string LoginName { get; set; }
public Guid? PhotoId { get; set; }
[Display(Name = "照片")]
[NotMapped]
public FileAttachment Photo { get; set; }
}

StudentController.cs
[ActionDescription("Sys.Get")]
[HttpGet("{id}")]
public StudentVM Get(string id)
{
//这个位置会报错
var vm = Wtm.CreateVM(id);
return vm;
}
跟踪代码，应该在 BaseCRUDVM.cs 进行修改
protected virtual TModel GetById(object Id)
...
把 foreach (var f in fa)
{
var fname = DC.GetFKName2(f.Name);
var fid = typeof(TModel).GetSingleProperty(fname).GetValue(rv);
if (fid != null)
{
var fp = Wtm.HttpContext.RequestServices.GetRequiredService();
var file = fp.GetFile(fid?.ToString(), false, DC);
rv.SetPropertyValue(f.Name, file);
}
}
里面的 var fid = typeof(TModel).GetSingleProperty(fname).GetValue(rv); 修改为
var fid = typeof(TModel).GetSingleProperty(fname)?.GetValue(rv);

―

**Comment by cfqdream** [comment]
我就是想如果需要定义photo,但是又不想用外键约束情况；

**Comment by liuliang-wt** [comment]
那样是不行的，框架需要附件跟FileAttachment关联
