### ISSUE TITLE
登录过期后点击修改、详情等页面跳转到登录页面登录成功后跳转的URL存在问题

### ISSUE THREAD

**Issue by mwb20** [dotnetcore/WTM#461]
**登录过期后点击修改、详情等页面跳转到登录页面登录成功后跳转的URL存在问题，应跳转到列表页面而不是修改等页面
重现步骤：进入任意列表页面（如：用户管理），清空浏览器Cookie然后点击任意一条数据的修改，跳转到登录页面，登录成功后即可重现。**
![image](https://user-images.githubusercontent.com/7752000/111896736-906fd200-8a56-11eb-8dfe-9f0fea1fc86c.png)

> 我的修复方法是在登录成功后对重定向url进行处理，在LoginController控制器类的 61行添加如下代码：

 `if (!url.StartsWith("/#") && url.Contains("#"))
 {
    url = "/" + url.Substring(url.LastIndexOf('#'));
}`

![image](https://user-images.githubusercontent.com/7752000/111896981-4851af00-8a58-11eb-99d7-8bdc7b9054a5.png)

**Comment by ram16g** [comment]
5.0.8 好像修复了这个问题，你是什么版本？

**Comment by ram16g** [comment]
https://github.com/dotnetcore/WTM/commit/834e89c82f941df8b3202d9c0feb6f226efe8d80 这个提交修复了

**Comment by liuliang-wt** [comment]
嗯，现在重新生成的项目，默认的这个文件已经修改了
