### ISSUE TITLE
隐藏搜索条件panel导致的操作列问题

### ISSUE THREAD

**Issue by dongyunsen** [dotnetcore/WTM#462]
![image](https://user-images.githubusercontent.com/58757576/112919867-79a63b00-913a-11eb-9a2b-479e7d183f97.png)

**Comment by dongyunsen** [comment]
checkbox列，序号列，操作列，都有问题

**Comment by liuliang-wt** [comment]
这应该是浏览器不兼容，新版本的框架将layui更新到了最新版，你可以试试

**Comment by dongyunsen** [comment]
最新版没问题
