### ISSUE TITLE
《菜单管理》新增的《目录》不可见

### ISSUE THREAD

**Issue by hohnworld** [dotnetcore/WTM#464]
按照视频操作添加的《目录》，左侧菜单一致没有出现，刷新、重启程序都没有
按照视频操作添加的《内部地址》勾选《外部》，左侧菜单也一致没有出现，刷新、重启程序都没有
版本信息：
WalkingTec.Mvvm.TagHelpers.LayUI" Version="5.1.1"
WalkingTec.Mvvm.Mvc" Version="5.1.1"

**Comment by hohnworld** [comment]
<PackageReference Include="WalkingTec.Mvvm.TagHelpers.LayUI" Version="5.1.1" />
    <PackageReference Include="WalkingTec.Mvvm.Mvc" Version="5.1.1" />

**Comment by hohnworld** [comment]
我方了：LayUI单一项目、前后分离的vue、还有老版本都一样

**Comment by hohnworld** [comment]
官网不能注册用户
https://community.walkingtec.cn/index/user/register.html

**Comment by liuliang-wt** [comment]
空目录就是不显示的


-------- 原始邮件 --------
发件人： hohnworld ***@***.***>
日期： 2021年4月2日周五 凌晨1:35
收件人： dotnetcore/WTM ***@***.***>
抄送： Subscribed ***@***.***>
主 题： Re: [dotnetcore/WTM] 《菜单管理》新增的《目录》不可见 (#464)

我方了：LayUI单一项目、前后分离的vue、还有老版本都一样

―
