### ISSUE TITLE
【SetCookie】失效

### ISSUE THREAD

**Issue by Newxml** [dotnetcore/WTM#465]
版本:  【5.x】【Vue】
环境:  【前端七牛云cdn】【后端 unbtun18.04 Kestrel】
问题描述：前端部署在七牛云上时，点击登录操作，
接口 /api/_Account/CheckUserInfo?ID=undefined  请求头上没有Cookie

**Comment by liuliang-wt** [comment]
5.1.4已经修改，appsettings文件中的CookieOptions里面可以指定"Domain"，比如"Domain":".abc.com",可以允许所有abc.com的二级域名设置cookie
