### ISSUE TITLE
wtm项目运行问题

### ISSUE THREAD

**Issue by yhj200722** [dotnetcore/WTM#470]
我在线上生成了一个项目，解压后可以直接运行。
然后我按照文档添加了School模型，把数据库删除了，重新运行项目也正常。
但是当我用dotnet ef migrations add InitialCreate生成了迁移的目录及文件，这时没有更新数据库，我运行项目，Startup文件中的Configure方法到app.UseWtmContext()这一步报错：System.NullReferenceException:“Object reference not set to an instance of an object。
现在我再把数据库删除了，运行依然报上面的错。
或者我把ef迁移生成的目录及文件删除了，运行还是报上面的错。
总结一下：只要用了ef生成了迁移文件，不管是否更新数据库，都一直出现上面的错误，我把新加的模型及数据库都删除了，还原到了最开始的状态，也一直报这个错误。
补充一下：我用的.net5，前后端分离vue版本，数据库是sqlserver，多项目。
另外wtm社区怎么注册，说要联系管理员？

**Comment by liuliang-wt** [comment]
我没能复现你的bug，你可以在qq群里找到我，把你报错的项目打包发给我。
社区总被人攻击，所以暂时不让注册了。

**Comment by yhj200722** [comment]
我发现了：ef迁移时会用到这个库Microsoft.EntityFrameworkCore.Design，如果用了最新的5.0.4和5.0.5版本就会出现上面的问题，我换成5.0.3就正常了
