### ISSUE TITLE
Blazor wasm模式发布后只能localhost访问

### ISSUE THREAD

**Issue by iioter** [dotnetcore/WTM#476]
blazor wasm版本client中的config固定指向了一个ip和端口，但是用户可能是通过外网、内网等不同网卡访问的项目，这样就导致页面请求不到api，导致生产环境无法使用wasm

**Comment by liuliang-wt** [comment]
5.2.2已修复，你可以生成同名项目，然后覆盖 Client项目中的program文件，和Shared项目中的WtmBlazorUtils目录。 client中的appsettings文件就可以不指定domains.server，默认使用浏览器上的访问地址
