### ISSUE TITLE
Blazor wasm发布无法使用压缩

### ISSUE THREAD

**Issue by iioter** [dotnetcore/WTM#479]
[按照微软文档](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression)，压缩不起作用，前端还是请求dll而不是.br

**Comment by ArgoZhang** [comment]
@whdwanghaidong 应该是哪里没有弄对，这个有几个步骤的，可以参见 
https://github.com/dotnetcore/BootstrapBlazor/blob/main/src/Wasm/BootstrapBlazor.WebAssembly.ClientHost/wwwroot/index.html

**Comment by iioter** [comment]
好的 再试试。blazor 666.写起来很舒服
