### ISSUE TITLE
前端选项卡建议增加右键关闭当前、关闭所有、关闭其他功能

### ISSUE THREAD

**Issue by gxiongxiong** [dotnetcore/WTM#48]

**Comment by LengYXin** [comment]
那个版本的？

**Comment by liuliang-wt** [comment]
layui版本已经有这个了，他肯定说的是react版本
![TIM截图20190904174935](https://user-images.githubusercontent.com/15852860/64244903-7afe8a00-cf3c-11e9-9527-e3c18ac6d450.png)

**Comment by alienwow** [comment]
我猜是layui

**Comment by LengYXin** [comment]
加完了 @gxiongxiong 
![image](https://user-images.githubusercontent.com/19631404/64324771-8d8ac900-cff9-11e9-9587-79e8702011c5.png)
