### ISSUE TITLE
用户对应的角色没有勾选的菜单仍然能通过网址打开并查询出数据（blazor版）

### ISSUE THREAD

**Issue by gxsww** [dotnetcore/WTM#480]
用户对应的角色没有勾选的菜单仍然能通过网址打开并查询出数据，只是没有新建，删除，导入导出等功能按钮，但数据能正常查询出来 ，数据行也没有相应操作按钮。后来用vue版测试没有这个问题，页面虽然能打开，但无法查询出数据的，我看了下它们的认证方式是不一样的，vue使用的是cookies,而blazor版使用的是jwt的认证方式，我不知道是不是因为这个原因才造成这样的问题，也不确定这个算不算bug,现在社区无法注册，所以只能发到这里，有知道如何解决这个问题的麻烦告知，谢谢了。

**Comment by liuliang-wt** [comment]
你是不是只设置了Client项目中的IsQuickDebug，在主项目中的配置文件里也有IsQuickDebug的设定。 在Wasm模式下，Client项目中的设定只负责前台判断是否要展示菜单和按钮， 主项目下的设置才是负责后台api是不是可以调用

**Comment by gxsww** [comment]
嗯，是的，现在可以了，感谢了！刚开始使用wtm，还不太熟悉。
