### ISSUE TITLE
Blazor wasm发布到IIS 上传图片报错

### ISSUE THREAD

**Issue by Qiulin-Git** [dotnetcore/WTM#482]
![YN9K86TW~YM1_4%0ZXU_B%W](https://user-images.githubusercontent.com/53858121/119588948-6b0b9580-be04-11eb-8df4-dd07685b8a52.jpg)
![image](https://user-images.githubusercontent.com/53858121/119589018-93938f80-be04-11eb-9415-b8d5705f803f.png)

Blazor 版的挂IIS上 用户图片上传报错，我看图片已经上传到服务器了

**Comment by ArgoZhang** [comment]
@Qiulin-Git 
能否给个 F12 的截图。是不是 404 错误，错误路径是什么？

**Comment by Qiulin-Git** [comment]
> @Qiulin - 吉特
> · 卡德 · 卡德 · 菲特是不是 404 错误，错误路径是什么？

![image](https://user-images.githubusercontent.com/53858121/120251219-7141bc00-c2b3-11eb-903f-7fcff4ff6624.png)

405 错误，  IIS 的 MIME 是有jpg格式，图片也上传到服务器了，服务器IIS 设置应该没有问题

**Comment by liuliang-wt** [comment]
IIS默认不支持Put，需要设置一下

**Comment by ArgoZhang** [comment]
@liuliang-wt 移除 `WebDav` 模块即可

**Comment by Qiulin-Git** [comment]
@liuliang-wt @ArgoZhang 
在web.config文件的system.webServer节点下 加入移除WebDAVModule 可以上传了
`
<modules>
   <remove name="WebDAVModule"/>
</modules>
`
