### ISSUE TITLE
Blazor版本菜单管理子项单独选择要选两次才能选中

### ISSUE THREAD

**Issue by Qiulin-Git** [dotnetcore/WTM#486]
![image](https://user-images.githubusercontent.com/53858121/120417879-264aa600-c392-11eb-95f3-21012fcfa5db.png)
官网下载的最新版本5.2.3的菜单管理还是有问题，子项单独选择要选两次才能选中 
比如选择用户管理，第一次选择 把页面名称、系统管理勾上了，第二次选择的时候才会把 用户管理 选中

**Comment by liuliang-wt** [comment]
@ArgoZhang 这好像是你控件的bug

**Comment by ArgoZhang** [comment]
@liuliang-wt 来个复现示例吧。这个树形跟 Checkbox 组合确实没有测试过

**Comment by ArgoZhang** [comment]
@liuliang-wt @Qiulin-Git 好厉害的 bug 还搞不定这个呢

**Comment by liuliang-wt** [comment]
@ArgoZhang 老张，不能知难而退啊，哈哈

**Comment by ArgoZhang** [comment]
@liuliang-wt 没，还在弄呢。今天出去一天没摸到电脑，刚开电脑

**Comment by ArgoZhang** [comment]
@liuliang-wt @Qiulin-Git 更新 5.0.36 已修复
