### ISSUE TITLE
Blazor版本当访问地址不存在时，网页直接崩溃死掉

### ISSUE THREAD

**Issue by Qiulin-Git** [dotnetcore/WTM#487]
![image](https://user-images.githubusercontent.com/53858121/120878098-cf8cd880-c5ec-11eb-963e-81f0002ed647.png)

标准的Blazor 程序当访问地址不存在时会执行到App.razor 下面 NotFound 节点，WTM的Blazor 当访问网页不存在直接就挂掉了，体验非常不好，哪怕给个404网页也比现在这样直接挂掉好

**Comment by liuliang-wt** [comment]
已修复
