### ISSUE TITLE
迁移数据库后，系统无法启动

### ISSUE THREAD

**Issue by iioter** [dotnetcore/WTM#488]
1.add-migration ini
2.update-database 生成数据库实例a
3.启动系统 连接数据库实例a报错无法启动，换成其他不存在的数据库实例一样报错。
使用的是blazor最新版
[RadarLineSource - 副本.zip](https://github.com/dotnetcore/WTM/files/6613667/RadarLineSource.-.zip)

**Comment by liuliang-wt** [comment]
这是因为你在datacontext项目里加了5.0.6的ef包，但是框架用的是5.0.5
