### ISSUE TITLE
AddDbContextFactory注入方式好像无法正常使用。

### ISSUE THREAD

**Issue by 5653325** [dotnetcore/WTM#494]
`public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    var connectionString =$"Host=127.0.0.1;Port=3306;User ID=root;Password=root;Database=test;Compress=false;Pooling=true;sslmode=none;";
                    services.AddDbContextFactory<DataContext>(option =>
                    {
                        option.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString));
                    });
                    services.AddHostedService<Worker>();
                });
    }`
Wrok代码
` public class Worker : BackgroundService
{
private readonly ILogger<Worker> _logger;
private readonly IDbContextFactory<DataContext> _contextFactory;
public Worker(ILogger<Worker> logger, IDbContextFactory<DataContext> contextFactory)
        {
            _logger = logger;
            _contextFactory = contextFactory;
        }
}`
运行时会报错：
Multiple constructors accepting all given argument types have been found in type 'DataAccess.DataContext'. There should only be one applicable constructor.

**Comment by liuliang-wt** [comment]
你直接在Worker里定义WtmContext就行，里面有DC

**Comment by 5653325** [comment]
谢谢解答，从文档中找到了。
https://wtmdoc.walkingtec.cn/#/Global/WtmContext

**Comment by 5653325** [comment]
谢谢解答，从文档中找到了。
https://wtmdoc.walkingtec.cn/#/Global/WtmContext
