### ISSUE TITLE
Blazor无法设置public页面如注册，找回密码等

### ISSUE THREAD

**Issue by wgz1989** [dotnetcore/WTM#497]
Blazor无法设置public页面如注册，找回密码等，app.razor使用的不是微软件的官网鉴权方法，导致公开页面也都需要获取到token才能访问

**Comment by liuliang-wt** [comment]
昨天发了5.3.1，已经修复了这个问题

Blazor模式中在页面上添加 @layout EmptyLayout 和 @attribute [Public] 属性，可以制作不受权限控制的独立的页面

**Comment by wgz1989** [comment]
@liuliang-wt 我昨天使用5.4.4测试，这个是不生效的，还是会跳到login

**Comment by liuliang-wt** [comment]
最新版本已经修复
