### ISSUE TITLE
主子表导入

### ISSUE THREAD

**Issue by MrSeaning** [dotnetcore/WTM#498]
我用的官方代码里的demo的WalkingTec.Mvvm.Demo项目，
![image](https://user-images.githubusercontent.com/7636910/126126947-cdcb37e5-1760-4a08-8647-95d39d68c1fc.png)
上图是 excel的数据，模板是下载的，报错信息如下
![image](https://user-images.githubusercontent.com/7636910/126127013-b1ce2328-34c8-49c7-9254-d395aa91912c.png)
版本 ：最新版5.3.1

**Comment by liuliang-wt** [comment]
Sorry,  是个bug，已修复源码，会在下一个版本发布。

发件人: ***@***.***>
发送时间: 2021年7月19日 16:19
收件人: ***@***.***>
抄送: ***@***.***>
主题: [dotnetcore/WTM] 主子表导入 (#498)


我用的官方代码里的demo的WalkingTec.Mvvm.Demo项目，
[image]<https://user-images.githubusercontent.com/7636910/126126947-cdcb37e5-1760-4a08-8647-95d39d68c1fc.png>
上图是 excel的数据，模板是下载的，报错信息如下
[image]<https://user-images.githubusercontent.com/7636910/126127013-b1ce2328-34c8-49c7-9254-d395aa91912c.png>
版本 ：最新版5.3.1

―
