### ISSUE TITLE
Blazor顶部导航下拉无效

### ISSUE THREAD

**Issue by 1gcat** [dotnetcore/WTM#500]
![QQ截图20210805114749](https://user-images.githubusercontent.com/43435652/128287932-a4c27f53-5a2b-4545-8346-f35a2edbe7f3.png)

语言选择和个人菜单均无效，这导致无法退出帐号。

**Comment by liuliang-wt** [comment]
这是由于bb控件库样式改变了，新建项目已修复。你可以参考https://github.com/dotnetcore/WTM/commit/b6e6bc97650f1e6b43ecd247fea1af9dea12db67 ， 手动改一下你项目中的这个文件
