### ISSUE TITLE
类生成文件异常

### ISSUE THREAD

**Issue by Hydma** [dotnetcore/WTM#507]
使用版本：5.4.5

我在添加实体类后，使用内置的“代码生成”功能，可以成功生成控制器和VM，但是没有生成视图。这是添加的第一个实体类。
![QQ截图20210829003116](https://user-images.githubusercontent.com/16333288/131224640-ff667d3c-ba1f-4169-8909-f73e957f64e6.png)
![QQ截图20210829003217](https://user-images.githubusercontent.com/16333288/131224641-dafc6909-b130-4ef9-a8ff-0453f6cc6381.png)

**Comment by liuliang-wt** [comment]
你是不是生成代码的时候，勾选了那个 “只生成Api” 。。。。

**Comment by Hydma** [comment]
> 你是不是生成代码的时候，勾选了那个 “只生成Api” 。。。。

我晕，犯了这个错误，是勾选了这个。我在项目开发的时候，默认没有勾选，自己新建的这个项目给自动勾选上了没注意。
