### ISSUE TITLE
切换菜单时，右侧页面发生抖动

### ISSUE THREAD

**Issue by raikay** [dotnetcore/WTM#523]
**效果如图**  
![](https://s3.bmp.ovh/imgs/2021/10/50142869afface84.gif)  
**生成参数**  
![](https://s3.bmp.ovh/imgs/2021/10/d174f8369c92a1b2.png)  
**运行环境**  
浏览器：Microsoft Edge  版本 94.0.992.47    
系统：Windos11   
显示器分辨率：1920 x 1080

**Comment by liuliang-wt** [comment]
额，就是这样。。。
