### ISSUE TITLE
多对多情况下使用Selector控件选择数据时搜索条件无效

### ISSUE THREAD

**Issue by jygzsjun** [dotnetcore/WTM#526]
在存在中间表的情况下，不管是否重写GetSelectorQuery，在vm里使用x.Searcher.x = *或者在Controller的get方法里使用vm.x.Searcher.x = *设置查询条件都不能按照条件筛选数据。

**Comment by liuliang-wt** [comment]
你可以在查询语句那里断点，看看Searcher里对应的变量有没有传过来，我这里测试了一下，但是没有复现你说的问题
