### ISSUE TITLE
建议给调试模式下,加入禁止npm启动的选项. 附代码

### ISSUE THREAD

**Issue by strugglesharp** [dotnetcore/WTM#550]
你们的 https://community.walkingtec.cn.根本注册不了.

vue的启动和后台的启动停止, 毕竟不是总是一致. 经常后台改点东西,一重启发现端口占用,原来是上次启动的前台没关,. 很麻烦.
而且一起启动, 两个日志混在一起, 发生点啥事都看不清.
我建议做成可配置关闭.
下面这个改动最小. 能做到configs结构中当然是最好了.

startup.cs中
```csharp
var isDisableStartNpm = configs.CurrentValue.AppSettings.TryGetValue("IsStartNpm", out string  isStartnpm) && isStartnpm == "false" ;
                if (env.IsDevelopment()  && !isDisableStartNpm)
                {
                    endpoints.MapToVueCliProxy(
                        "{*path}",
                        new SpaOptions { SourcePath = "ClientApp" },
                        npmScript: "start",
                        regex: "Compiled successfully");
                }
```
appsettings.json中
``` 
 "AppSettings": {
        "IsStartNpm": "false",
        "key1": "value1",
        "key2": "value2"
    }
```

**Comment by liuliang-wt** [comment]
论坛天天有人攻击，后续会换一种方式
vue的项目有自带的api only的启动配置，你要是只想启动后台，用api only启动就好

**Comment by strugglesharp** [comment]
> 

api only 试过, 不行.
你的api only 与  自宿主运行,就差一个"launchUrl": "swagger", 没什么用.  
按照代码逻辑, 要不要npm run start, 是靠  env.IsDevelopment().  应该是关联了"ASPNETCORE_ENVIRONMENT": "Development",  你的api only 也是Development
但ASPNETCORE_ENVIRONMENT这个变量,  指向太模糊, 不知道其他地方会不会用, 所以 不敢贸然改动他.

**Comment by strugglesharp** [comment]
> 论坛天天有人攻击，后续会换一种方式 vue的项目有自带的api only的启动配置，你要是只想启动后台，用api only启动就好

api only 试过, 不行.
你的api only 与  自宿主运行,就差一个"launchUrl": "swagger", 没什么用.  
按照代码逻辑, 要不要npm run start, 是靠  env.IsDevelopment().  应该是关联了"ASPNETCORE_ENVIRONMENT": "Development",  你的api only 也是Development
但ASPNETCORE_ENVIRONMENT这个变量,  指向太模糊, 不知道其他地方会不会用, 所以 不敢贸然改动他.

```
{
  "profiles": {
    "我的工程名XXX": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      },
      "applicationUrl": "http://localhost:6949/"
    },
    "ApiOnly": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      },
      "applicationUrl": "http://localhost:6949/"
    }
  }
}

```

**Comment by liuliang-wt** [comment]
可能是下载的项目这个默认文件不对，应该是这种
    "ApiOnly": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      },
      "applicationUrl": "http://localhost:7598/"
    }
你是官网上生成的项目么

**Comment by strugglesharp** [comment]
https://wtmdoc.walkingtec.cn/setup
非plus版本生的.

你的plus版本生成的vue版本,没有本地代码生成功能, 我没用plus

> 可能是下载的项目这个默认文件不对，应该是这种 "ApiOnly": { "commandName": "Project", "launchBrowser": true, "launchUrl": "swagger", "environmentVariables": { "ASPNETCORE_ENVIRONMENT": "Production" }, "applicationUrl": "http://localhost:7598/" } 你是官网上生成的项目么

**Comment by strugglesharp** [comment]
https://wtmdoc.walkingtec.cn/setup
生成的, 都不是 "ASPNETCORE_ENVIRONMENT": "Production"

**Comment by liuliang-wt** [comment]
好，这个我也改一下

**Comment by liuliang-wt** [comment]
已修复
