### ISSUE TITLE
docker运行字体问题

### ISSUE THREAD

**Issue by roadinger** [dotnetcore/WTM#555]
SixLabors.Fonts.Exceptions.FontFamilyNotFoundException:“Times New Roman could not be found”
Times New Roman缺少   dockerfile如何处理 ？

**Comment by liuliang-wt** [comment]
安装这个字体，或者你升级到最新版本，最新版本修改了逻辑，会寻找系统默认字体，而不是指定字体

**Comment by roadinger** [comment]
最新版本会加载系统第一个字体，代码：SystemFonts.Families.First()
dockerfile 添加下面这句：
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install -y fontconfig \
	&& apt-get clean && apt-get autoclean && apt-get autoremove \
	&& rm -rf /var/lib/apt/lists/*

已解决
