### ISSUE TITLE
LayUI使用ueditor 编辑页面展示不了内容

### ISSUE THREAD

**Issue by weiguang3100** [dotnetcore/WTM#572]
文章内容使用 代码段功能，如果里面有换行，入库之后编辑页面展示不了，比如这段代码 
<pre class="brush:js;toolbar:false">var num =2.446242342;
num = num.toFixed(2);
console.log(num); 
console.log(typeof num);</pre>
<p>
    2、Math.floor()，不四舍五入 ，向下取整不改变数据类型
</p>
<pre class="brush:js;toolbar:false">num = Math.floor(num * 100) / 100;
console.log(num); 
console.log(typeof num); </pre>

入库之后点击编辑页面会报错，展示不出来，是哪个地方设置不正常吗，看文档 加[StringNeedLTGT]了，也没法解决问题

**Comment by liuliang-wt** [comment]
你需要在添加和修改的controller方法上加[StringNeedLTGT]， 不是在显示的时候加

**Comment by weiguang3100** [comment]
> 你需要在添加和修改的controller方法上加[StringNeedLTGT]， 不是在显示的时候加
我是在文章的Controller Create,Edit上加的，不加的话，html标记不能正常显示，加上了可以显示了，但是如果使用代码块 pre标记的话，里面有换行的话，添加到数据库之后，再显示的时候，ueditor setcontent的时候好像是有换行，导致内容不对报错，麻烦帮忙看下是不是我设置的地方不对
`[ActionDescription("文章管理")]
    public partial class ArticleController : BaseController
    {
        #region Create
        [StringNeedLTGT]
        [ActionDescription("Sys.Create")]
        public ActionResult Create()
        {
            var vm = Wtm.CreateVM<ArticleVM>();
            return PartialView(vm);
        }

        [HttpPost]
        [StringNeedLTGT]
        [ActionDescription("Sys.Create")]
        public ActionResult Create(ArticleVM vm)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(vm);
            }
            else
            {
                vm.DoAdd();
                if (!ModelState.IsValid)
                {
                    vm.DoReInit();
                    return PartialView(vm);
                }
                else
                {
                    return FFResult().CloseDialog().RefreshGrid();
                }
            }
        }
        #endregion`

**Comment by weiguang3100** [comment]
`output.PostElement.AppendHtml($@"
<input type='hidden' name='hiddenContent' id='hiddenContent' value='{ (DefaultValue != null ? DefaultValue.ToString() : Field?.Model?.ToString())}' />
<script>
  layui.use(['ueditorconfig'], function () {{
    layui.ueditor.loadEditor('{Id}').ready(function(){{this.setContent($('#hiddenContent').val())}});
  }});
</script>
");`
修改源码暂时解决问题， @liuliang-wt 麻烦帮忙看下这样改合适不
