### ISSUE TITLE
wt:combobox的required="false"不生效

### ISSUE THREAD

**Issue by 5653325** [dotnetcore/WTM#596]
实体中 ParentId为int类型，在页面上使用以下声明方式
<wt:combobox field="Entity.ParentId" items="AllModules" required="false" />
此下拉框仍然是必填项。
期望是设置required="false" 后，此下拉框可不选择内容。

**Comment by liuliang-wt** [comment]
是否必填取决于他绑定的字段， 如果你ParentId字段是可为空的，那就是非必填

**Comment by 5653325** [comment]
3q
