### ISSUE TITLE
6.3.20(含)版本以後導出excel後再查詢日期被鎖定初始值的問題

### ISSUE THREAD

**Issue by cct0831** [dotnetcore/WTM#605]
6.3.20(含)版本以後，當畫面有日期欄位，點擊查詢後導出excel，再點擊查詢，日期條件都會被初始化，但畫面上日期控件的日期不會被修改，值已經被鎖定，導致查詢無效。

例如畫面上有個日期起迄，預設2023/6/11~2023/6/12，選取2023/06/1~2023/6/2後點擊查詢，再點擊下載將數據導出excel，這時再點擊查詢，就會發現查詢結果是2023/6/11~2023/6/12的數據，但畫面上的日期仍然停留在2023/06/1~2023/6/2，怎麼修改都不會生效，只能關閉頁面才能再度使用。

請協助解決，謝謝

**Comment by liuliang-wt** [comment]
确实有这个问题，下个版本会修复

**Comment by liuliang-wt** [comment]
6.3.27已修复

**Comment by cct0831** [comment]
已驗證沒有問題，謝謝
