### ISSUE TITLE
在Docker环境中，无法正确加载资源中的中文信息，一直是英文。

### ISSUE THREAD

**Issue by 5653325** [dotnetcore/WTM#606]
目前使用的是Windows版本的Docker Desktop来进行的镜像打包和镜像分发。
操作系统是最新版Win11
Docker Desktop版本是Docker Desktop 4.20.1
Docker中的Linux系统版本是Debian GNU/Linux 10
Docker中的Linux系统详细信息是Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

appsettings.json中的Languages值为zh

打包镜像的Dockerfile已经把时区调整为中国时区（Asia/Shanghai）
![R_`DMV( C_9H73}ODIUWYYA](https://github.com/dotnetcore/WTM/assets/3361135/30fea7a2-0391-477d-9bba-8b3549c4ddde)

但在Docker镜像运行后访问，得到的仍然是英文的提示信息：
![ZOZ0CFHB4E596WBE48}FBLY](https://github.com/dotnetcore/WTM/assets/3361135/a313416c-0294-4d8e-b65e-e987387c6638)

**Comment by liuliang-wt** [comment]
这个不是显示的英文，这个是找不到资源文件，所以显示的是资源文件里的key值

**Comment by 5653325** [comment]
> 这个不是显示的英文，这个是找不到资源文件，所以显示的是资源文件里的key值

是需要把某个文件单独打包进去？我用的是release发布的，我看docker的项目文件夹里是有zh/xxx.resources.dll文件存在的。

**Comment by 5653325** [comment]
大佬有没有解决办法？在服务器正常，在docker中显示不了资源文件中的文字描述（docker的项目文件夹里是有zh/xxx.resources.dll文件）
