### ISSUE TITLE
解决下上传问题吧? 没提交 选择文件--就已经自动上传了-- 选择错文件也上传 造成很多垃圾文件 测试版本LayUI

### ISSUE THREAD

**Issue by AtlantisDe** [dotnetcore/WTM#611]
# ``解决下上传问题吧? 测试版本LayUI``

```c#
解决下上传问题吧?没提交 选择就已经上传 选择错文件也上传 造成很多垃圾文件 测试版本LayUI

//当前已经使用最新WTM 源码测试.

我以为修复了 这么久 还是存在这个问题.
```

<img width="542" alt="WTM-Upload-Bug-001" src="https://github.com/dotnetcore/WTM/assets/39150678/83ac1aee-e523-449b-bb9b-8c31a83c1ba5">

**Comment by 5653325** [comment]
建议屏蔽掉自带的文件上传接口，自己搞吧。
