### ISSUE TITLE
外部菜单怎么用？

### ISSUE THREAD

**Issue by Code-Fight** [dotnetcore/WTM#62]
我的理解是可以在框架中加载一个外部的菜单
但是我发现现在不好用
请求的地址是[http://localhost:53065/#/http://www.baidu.com]
这样的一个地址
请问是否使用方式不对

**Comment by liuliang-wt** [comment]
当前版本的外部菜单有点问题，下个版本会修复

**Comment by LengYXin** [comment]
React 中的 直接配置一个 http://www.baidu.com 就能使用

**Comment by Code-Fight** [comment]
ok
等下一个版本
