### ISSUE TITLE
Workflow运行时部分情况无法正确读取Model的Property

### ISSUE THREAD

**Issue by KVM-Explorer** [dotnetcore/WTM#629]
在WalkingTec.Mvvm.Mvc 6.4.7版本可以正确读取Model的Property，但是6.4.8版本到6.5.1存在部分情况下无法读取Model属性信息，其Workflow定义如下

![image](https://github.com/dotnetcore/WTM/assets/57474521/8e099bdc-936b-4279-9ff7-cb5c64d7350d)

workflowContext.Name = "JavaScript"

但是对于部分Model如
```
public class AppUserBasic : BasePoco,IWorkflow
    {
        public string Account { get; set; }

    }
```
新老版本都能正常识别运行

但是有的Model运行无法读取Model的Property的值

    
![image](https://github.com/dotnetcore/WTM/assets/57474521/e1fae58b-9317-4cc9-9f0a-bb435b74a1e3)
{
 "Type": "Jint.Runtime.JavaScriptException",
 "Message": "Cannot read property 'ApprovalComment' of null",
 "StackTrace": "   at <anonymous>:1:17",
 "InnerException": null,
 "Data": {}
}
![image](https://github.com/dotnetcore/WTM/assets/57474521/686c2dbb-c8e2-4515-8b94-d093b783a0ea)

workflowContext.ApprovalComment = 'Workflow Run Success'
```
[Table("ReservationBasics")]
 public class ReservationBasic : BasePoco
    {
        public Guid ApplicantId { get; set; }
        public AppUserBasic Applicant { get; set; }
    }
[Table("ReservationApplies")]
    public class ReservationApply : ReservationBasic ,IWorkflow
    {
        public List<ApplicationParticipationMT> Participants { get; set; }
        public string ApprovalComment { get; set; } = string.Empty;
    }
    [MiddleTable]
    public class ApplicationParticipationMT : BasePoco
    {
        public Guid ReservationApplyId { get; set; }
        public ReservationApply ReservationApply { get; set; }
        public Guid? AppUserId { get; set; }
        public AppUserBasic AppUser { get; set; }
    }
```

**Comment by KVM-Explorer** [comment]
我生成了一个新的项目进行测试，发现应该和外键关联部分相关，Elsa Workflow在含有外键关联的Model会出现问题，Workflow位于项目中Workflows文件夹下
[BugTest.zip](https://github.com/dotnetcore/WTM/files/13407192/BugTest.zip)

**Comment by liuliang-wt** [comment]
6.5.2已修复
