### ISSUE TITLE
domain还是失效了？

### ISSUE THREAD

**Issue by YenseanHub** [dotnetcore/WTM#631]
版本: 【WTM版本6.5.2】【Vue】
环境: 前后端分离，部署在IIS上，前端后台管理域名：mapadmin.yensean.com, 后端部署域名：mapapi.yensean.com
问题描述：在cookieoption中设置了domain：“.yensean.com”，但是登录成功后，在访问 /api/_Account/CheckUserInfo?ID=XXXX 请求头上没有Cookie的设置，导致一直跳转
是不是还有其他设置？
困扰几天，望指教，已经donate，支持作者，谢谢。
![{EB)4Y6XA~MBW8M KSIXMXA_tmb](https://github.com/dotnetcore/WTM/assets/29721016/4b47c0b8-bf5c-49f6-9183-9d51e56cdd6b)

**Comment by liuliang-wt** [comment]
前后端分里的是不用cookie的，用的是jwt的token

**Comment by YenseanHub** [comment]
谢谢回复了，
最后如果前端分离用的cookie需要：
1、后端设置cookie的security，还有samesite 是none
2、前端需要带上withCredentials: true
