### ISSUE TITLE
前后端分离的问题

### ISSUE THREAD

**Issue by tiger2014** [dotnetcore/WTM#7]
介绍上说：“从2.2.8开始，WTM框架开始支持前后端分离的模式”，那现在的版本有前后端分离吗？

**Comment by liuliang-wt** [comment]
因为后期都是nuget包了，我们也提供了线上一键创建项目的功能，就没有在GitHub上发布Release了。你可以直接在文档的连接中在线新建项目，那会自动用最新的版本。现在最新的版本是2.2.21 。目前前后端分离模式可以使用，但还是预览版，我们需要实践几个真实项目才能正式发布。
