### ISSUE TITLE
IE11点击登录后一直停留加载中。。

### ISSUE THREAD

**Issue by mic277203** [dotnetcore/WTM#71]
原因可能是 View.js 的 endsWith 方法是ES6的特性

**Comment by liuliang-wt** [comment]
@alienwow 好像还真是，你看一下，layuiadmin本身在IE11下可以看

**Comment by liuliang-wt** [comment]
@mic277203  已修复，新生成的项目没问题了，老项目可以手动更新一下这个文件：
https://github.com/dotnetcore/WTM/blob/master/demo/WalkingTec.Mvvm.Demo/wwwroot/layuiadmin/lib/view.js

**Comment by mic277203** [comment]
@liuliang-wt 非常感谢
