### ISSUE TITLE
ITreeData 主键

### ISSUE THREAD

**Issue by wayne2006** [dotnetcore/WTM#73]
框架更新为自定义主键后，ITreeData接口的ParentId  还是 Guid 类型。

![image](https://user-images.githubusercontent.com/21210915/65228725-8e455400-dafd-11e9-9d27-5325c382dd15.png)

**Comment by liuliang-wt** [comment]
是的，目前这般Tree结构还不能支持自定义主键，我还在思考更好的方案

**Comment by wayne2006** [comment]
好的，谢谢！
