### ISSUE TITLE
后台返回的弹层 移动端显示不正常

### ISSUE THREAD

**Issue by 2821840032** [dotnetcore/WTM#79]
![image](https://user-images.githubusercontent.com/29800454/65417456-a209f680-de2c-11e9-83df-29799b883530.png)
就像这样 Dialog宽度超出浏览器

GridActionExtensions类中的函数
![image](https://user-images.githubusercontent.com/29800454/65417603-fd3be900-de2c-11e9-952c-109ef9c3911e.png)
这里为空则默认800

如果能自动展开最大化是最好的，但是layui 的open好像没有提供这个参数
![image](https://user-images.githubusercontent.com/29800454/65417895-bbf80900-de2d-11e9-833f-028dc43614e3.png)
这样移动端看起来是最舒服的。

所以 希望把GridActionExtensions 函数中的 
 DialogWidth = dialogWidth ?? 800 改成 DialogWidth = dialogWidth;
或者前段的OpenDialog函数中
能添加对宽度的判断，宽度超过浏览器则最大化。

**Comment by liuliang-wt** [comment]
已修复
