### ISSUE TITLE
Transfer 穿梭框 显示问题

### ISSUE THREAD

**Issue by wayne2006** [dotnetcore/WTM#80]
当把 Transfer 穿梭框 的enable-search 改为 false后，就没有滚动条了。
![image](https://user-images.githubusercontent.com/21210915/65475712-15eee200-deb3-11e9-88e1-e5151bcf409b.png)
显示结果：
![image](https://user-images.githubusercontent.com/21210915/65475731-2bfca280-deb3-11e9-92f5-2c3fe172e554.png)
浏览器版本：
Google Chrome 已是最新版本
版本 77.0.3865.90（正式版本） （64 位）

补充：
发现 提交保存后 不能将值传递回vm中，不能保存到数据库中。

**Comment by wayne2006** [comment]
点击穿梭按钮的时候，控制台会报错
![image](https://user-images.githubusercontent.com/21210915/65476951-3f117180-deb7-11e9-9db0-e1c2006dd9fe.png)

**Comment by wayne2006** [comment]
![image](https://user-images.githubusercontent.com/21210915/65477918-6c135380-deba-11e9-86b5-e87812f5f384.png)
input[name=Entity.ProvinceCode]  这里没有单引号，报错！
![image](https://user-images.githubusercontent.com/21210915/65477962-91a05d00-deba-11e9-9f3b-06ae4d523426.png)

**Comment by liuliang-wt** [comment]
@alienwow  看一下
