### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by 51zhaoshi** [dotnetcore/WTM#95]
新版swagger不能正常使用，报错  Failed to load API definition，Internal Server Error /swagger/v1/swagger.json。
1.跟踪调试控制台报错System.NotSupportedException: Ambiguous HTTP method for action - WalkingTec.Mvvm.Admin.Api._ActionLogController.RedoValidation (WalkingTec.Mvvm.Mvc.Admin). Actions require an explicit HttpMethod binding for Swagger 2.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)；
2.查看源代码，应该是BaseApiController中，RedoValidation的问题。

**Comment by liuliang-wt** [comment]
@51zhaoshi 是的，已经修改了，近期发布

**Comment by alienwow** [comment]
v2.3.8
