### ISSUE TITLE
话说菜单目录怎么设置为中文啊？_Admin这种形式也太不友好了吧~~

### ISSUE THREAD

**Issue by w821759016** [dotnetcore/WTM#96]

**Comment by liuliang-wt** [comment]
@w821759016 项目默认是调试模式，也是我们推荐的开发过程中使用的模式。调试模式会反射你所有controller形成左边的菜单，而不会读取你配置的菜单，并且跳过权限验证，让你开发调试更快捷。 Appsettings文件中修改IsQuickDebug设置可以关闭调试模式，具体可以参考文档中的faq部分。谢谢

**Comment by w821759016** [comment]
了解，谢谢。
